export interface RepairReceipt {
    ObjID: Number,
    CompanyCode: Number,
    BranchCode: string,
    RepairNo: Number,
    CustID: Number,
    CustName: string,
    RepairDate: Date,
    SalCode: string,
    OperatorCode: string,
    DueDate: Date,
    TagWt: Number,
    CFlag: string,
    IssueNo: Number,
    RepairItems: string,
    CancelledBy: string,
    Remarks: string,
    CustDueDate: Date,
    UpdateOn: Date,
    ShiftID: Number,
    NewBillNo: string,
    Address1: string,
    Address2: string,
    Address3: string,
    City: string,
    PinCode: string,
    MobileNo: string,
    State: string,
    StateCode: Number,
    TIN: string,
    PANNo: string,
    lstOfRepairReceiptDetails:[]
}

export interface RepairItemDetails{
    ObjID: Number,
      CompanyCode: string,
      BranchCode: string,
      RepaireNo: Number,
      SlNo: Number,
      Item: string,
      Units: Number,
      GrossWt: Number,
      StoneWt: Number,
      NetWt: Number,
      Description: string,
      UpdateOn: Date,
      GSCode:  string,
      FinYear: Number,
      Rate: Number,
      PartyCode: Number,
      Dcts: Number
}