export class TagSplit{
    ObjID: null;
    CompanyCode: null;
    BranchCode: null;
    BarcodeNo: null;
    BatchNo: null;
    SalCode: null;
    OperatorCode: null;
    Date:null;
    CouterCode :null;
    GSCode :null;
    ItemName: null;
    Gwt: null;
    Swt: null;
    Nwt: null;
    Grade: null;
    CatalogID: null;
    MakingChargePerRs: null;
    WastePercent: null;
    Qty: null;
    ItemSize: null;
    DesignNo: null;
    PieceRate: null;
    DiamondAmount: null;
    StoneAmount: null;
    OrderNo: null;
    SoldFlag: null;
    ProductCode: null;
    HallmarkCharges: null;
    Remarks: null;
    SupplierCode: null;
    OrderedCompanyCode: null;
    OrderedBranchCode: null;
    Karat: null;
    McAmount: null;
    WastageGrams: null;
    McPercent: null;
    McType: null;
    OldBarcodeNo: null;
    ProdIda: null;
    ProdTagno: null;
    UpdateOn: null;
    LotNo: null;
    TagWt: null;
    IsConfirmed: null;
    ConfirmedBy: null;
    ConfirmedDate: null;
    CurrentWt: null;
    MCFor: null;
    DiamondNo: null;
    BatchId: null;
    AddWt: null;
    WeightRead: null;
    ConfirmedweightRead: null;
    PartyName: null;
    DesignName: null;
    ItemSizeName: null;
    MasterDesignCode: null;
    MasterDesignName: null;
    VendorModelNo: null;
    PurMcGram: null;
    McPerPiece: null;
    TaggingType: null;
    BReceiptNo: null;
    BSNo: null;
    IssueTo: null;
    PurMcAmount: null;
    PurMcType: null;
    PurRate: null;
    SRBatchID: null;
    TotalSellingMC: null;
    PurDiamondAmount:null;
    TotalPurchaseMc:null;
    PurStoneAmount:null;
    PurPurityPercentage:null;
    PurWastageType:null;
    PurWastageTypeValue:null;
    UniqRowID:null;
    CertificationNo:null;
    RefNo:null;
    ReceiptType:null;
    EntryDocType:null;
    EntryDate:null;
    EntryDocNo:null;
    ExitDocType:null;
    ExitDate:null;
    ExitDocNo:null;
    OnlineStock:null;
    IsShuffled:null;
    Shuffled_date:null;
    Collections:null;
    lstOfStone:[
        {
            ObjID: null;
            CompanyCode: null;
            BranchCode: null;
            BillNo: null;
            SlNo: null;
            EstNo: null;
            EstSrNo: null;
            BarcodeNo: null;
            Type: null;
            Name: null;
            Qty: null;
            Carrat: null;
            StoneWt: null;
            Rate: null;
            Amount: null;
            Tax: null;
            TaxAmount: null;
            TotalAmount: null;
            BillType: null;
            DealerSalesNo: null;
            BillDet11PK: null;
            UpdateOn: null;
            FinYear: null;
            Color: null;
            Clarity: null;
            Shape: null;
            Cut: null;
            Polish: null;
            Symmetry: null;
            Fluorescence: null;
            Certificate: null
        }
    ];
}


