//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ProdigyAPI.ShipmentIntegration.com.bluedart.netconnect.pickup {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IPickupRegistration", Namespace="http://tempuri.org/")]
    public partial class PickupRegistration : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback RegisterPickupOperationCompleted;
        
        private System.Threading.SendOrPostCallback CancelPickupOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllProductsAndSubProductsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PickupRegistration() {
            this.Url = global::ProdigyAPI.ShipmentIntegration.Properties.Settings.Default.ProdigyAPI_ShipmentIntegration_com_bluedart_netconnect_pickup_PickupRegistration;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event RegisterPickupCompletedEventHandler RegisterPickupCompleted;
        
        /// <remarks/>
        public event CancelPickupCompletedEventHandler CancelPickupCompleted;
        
        /// <remarks/>
        public event GetAllProductsAndSubProductsCompletedEventHandler GetAllProductsAndSubProductsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IPickupRegistration/RegisterPickup", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public PickupRegistrationResponse RegisterPickup([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] PickupRegistrationRequest request, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] UserProfile profile) {
            object[] results = this.Invoke("RegisterPickup", new object[] {
                        request,
                        profile});
            return ((PickupRegistrationResponse)(results[0]));
        }
        
        /// <remarks/>
        public void RegisterPickupAsync(PickupRegistrationRequest request, UserProfile profile) {
            this.RegisterPickupAsync(request, profile, null);
        }
        
        /// <remarks/>
        public void RegisterPickupAsync(PickupRegistrationRequest request, UserProfile profile, object userState) {
            if ((this.RegisterPickupOperationCompleted == null)) {
                this.RegisterPickupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegisterPickupOperationCompleted);
            }
            this.InvokeAsync("RegisterPickup", new object[] {
                        request,
                        profile}, this.RegisterPickupOperationCompleted, userState);
        }
        
        private void OnRegisterPickupOperationCompleted(object arg) {
            if ((this.RegisterPickupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegisterPickupCompleted(this, new RegisterPickupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IPickupRegistration/CancelPickup", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public CancelPickupResponseEntity CancelPickup([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] CancelPickupRequest request, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] UserProfile profile) {
            object[] results = this.Invoke("CancelPickup", new object[] {
                        request,
                        profile});
            return ((CancelPickupResponseEntity)(results[0]));
        }
        
        /// <remarks/>
        public void CancelPickupAsync(CancelPickupRequest request, UserProfile profile) {
            this.CancelPickupAsync(request, profile, null);
        }
        
        /// <remarks/>
        public void CancelPickupAsync(CancelPickupRequest request, UserProfile profile, object userState) {
            if ((this.CancelPickupOperationCompleted == null)) {
                this.CancelPickupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelPickupOperationCompleted);
            }
            this.InvokeAsync("CancelPickup", new object[] {
                        request,
                        profile}, this.CancelPickupOperationCompleted, userState);
        }
        
        private void OnCancelPickupOperationCompleted(object arg) {
            if ((this.CancelPickupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CancelPickupCompleted(this, new CancelPickupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IPickupRegistration/GetAllProductsAndSubProducts", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public GetAllProductsAndSubProductsResponseEntity GetAllProductsAndSubProducts([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] UserProfile profile) {
            object[] results = this.Invoke("GetAllProductsAndSubProducts", new object[] {
                        profile});
            return ((GetAllProductsAndSubProductsResponseEntity)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllProductsAndSubProductsAsync(UserProfile profile) {
            this.GetAllProductsAndSubProductsAsync(profile, null);
        }
        
        /// <remarks/>
        public void GetAllProductsAndSubProductsAsync(UserProfile profile, object userState) {
            if ((this.GetAllProductsAndSubProductsOperationCompleted == null)) {
                this.GetAllProductsAndSubProductsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllProductsAndSubProductsOperationCompleted);
            }
            this.InvokeAsync("GetAllProductsAndSubProducts", new object[] {
                        profile}, this.GetAllProductsAndSubProductsOperationCompleted, userState);
        }
        
        private void OnGetAllProductsAndSubProductsOperationCompleted(object arg) {
            if ((this.GetAllProductsAndSubProductsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllProductsAndSubProductsCompleted(this, new GetAllProductsAndSubProductsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SAPI.Entities.Pickup")]
    public partial class PickupRegistrationRequest {
        
        private string[] aWBNoField;
        
        private string areaCodeField;
        
        private bool cISDDNField;
        
        private bool cISDDNFieldSpecified;
        
        private string contactPersonNameField;
        
        private string customerAddress1Field;
        
        private string customerAddress2Field;
        
        private string customerAddress3Field;
        
        private string customerCodeField;
        
        private string customerNameField;
        
        private string customerPincodeField;
        
        private string customerTelephoneNumberField;
        
        private string doxNDoxField;
        
        private string emailIDField;
        
        private bool isForcePickupField;
        
        private bool isForcePickupFieldSpecified;
        
        private bool isReversePickupField;
        
        private bool isReversePickupFieldSpecified;
        
        private string mobileTelNoField;
        
        private int numberofPiecesField;
        
        private bool numberofPiecesFieldSpecified;
        
        private string officeCloseTimeField;
        
        private string packTypeField;
        
        private string productCodeField;
        
        private string referenceNoField;
        
        private string remarksField;
        
        private string routeCodeField;
        
        private System.DateTime shipmentPickupDateField;
        
        private bool shipmentPickupDateFieldSpecified;
        
        private string shipmentPickupTimeField;
        
        private string[] subProductsField;
        
        private double volumeWeightField;
        
        private bool volumeWeightFieldSpecified;
        
        private double weightofShipmentField;
        
        private bool weightofShipmentFieldSpecified;
        
        private bool isToPayShipperField;
        
        private bool isToPayShipperFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] AWBNo {
            get {
                return this.aWBNoField;
            }
            set {
                this.aWBNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AreaCode {
            get {
                return this.areaCodeField;
            }
            set {
                this.areaCodeField = value;
            }
        }
        
        /// <remarks/>
        public bool CISDDN {
            get {
                return this.cISDDNField;
            }
            set {
                this.cISDDNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CISDDNSpecified {
            get {
                return this.cISDDNFieldSpecified;
            }
            set {
                this.cISDDNFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ContactPersonName {
            get {
                return this.contactPersonNameField;
            }
            set {
                this.contactPersonNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CustomerAddress1 {
            get {
                return this.customerAddress1Field;
            }
            set {
                this.customerAddress1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CustomerAddress2 {
            get {
                return this.customerAddress2Field;
            }
            set {
                this.customerAddress2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CustomerAddress3 {
            get {
                return this.customerAddress3Field;
            }
            set {
                this.customerAddress3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CustomerCode {
            get {
                return this.customerCodeField;
            }
            set {
                this.customerCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CustomerName {
            get {
                return this.customerNameField;
            }
            set {
                this.customerNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CustomerPincode {
            get {
                return this.customerPincodeField;
            }
            set {
                this.customerPincodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CustomerTelephoneNumber {
            get {
                return this.customerTelephoneNumberField;
            }
            set {
                this.customerTelephoneNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DoxNDox {
            get {
                return this.doxNDoxField;
            }
            set {
                this.doxNDoxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EmailID {
            get {
                return this.emailIDField;
            }
            set {
                this.emailIDField = value;
            }
        }
        
        /// <remarks/>
        public bool IsForcePickup {
            get {
                return this.isForcePickupField;
            }
            set {
                this.isForcePickupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsForcePickupSpecified {
            get {
                return this.isForcePickupFieldSpecified;
            }
            set {
                this.isForcePickupFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool IsReversePickup {
            get {
                return this.isReversePickupField;
            }
            set {
                this.isReversePickupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsReversePickupSpecified {
            get {
                return this.isReversePickupFieldSpecified;
            }
            set {
                this.isReversePickupFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MobileTelNo {
            get {
                return this.mobileTelNoField;
            }
            set {
                this.mobileTelNoField = value;
            }
        }
        
        /// <remarks/>
        public int NumberofPieces {
            get {
                return this.numberofPiecesField;
            }
            set {
                this.numberofPiecesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumberofPiecesSpecified {
            get {
                return this.numberofPiecesFieldSpecified;
            }
            set {
                this.numberofPiecesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OfficeCloseTime {
            get {
                return this.officeCloseTimeField;
            }
            set {
                this.officeCloseTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PackType {
            get {
                return this.packTypeField;
            }
            set {
                this.packTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ProductCode {
            get {
                return this.productCodeField;
            }
            set {
                this.productCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ReferenceNo {
            get {
                return this.referenceNoField;
            }
            set {
                this.referenceNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RouteCode {
            get {
                return this.routeCodeField;
            }
            set {
                this.routeCodeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ShipmentPickupDate {
            get {
                return this.shipmentPickupDateField;
            }
            set {
                this.shipmentPickupDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ShipmentPickupDateSpecified {
            get {
                return this.shipmentPickupDateFieldSpecified;
            }
            set {
                this.shipmentPickupDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ShipmentPickupTime {
            get {
                return this.shipmentPickupTimeField;
            }
            set {
                this.shipmentPickupTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] SubProducts {
            get {
                return this.subProductsField;
            }
            set {
                this.subProductsField = value;
            }
        }
        
        /// <remarks/>
        public double VolumeWeight {
            get {
                return this.volumeWeightField;
            }
            set {
                this.volumeWeightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VolumeWeightSpecified {
            get {
                return this.volumeWeightFieldSpecified;
            }
            set {
                this.volumeWeightFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double WeightofShipment {
            get {
                return this.weightofShipmentField;
            }
            set {
                this.weightofShipmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WeightofShipmentSpecified {
            get {
                return this.weightofShipmentFieldSpecified;
            }
            set {
                this.weightofShipmentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool isToPayShipper {
            get {
                return this.isToPayShipperField;
            }
            set {
                this.isToPayShipperField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isToPayShipperSpecified {
            get {
                return this.isToPayShipperFieldSpecified;
            }
            set {
                this.isToPayShipperFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SAPI.Entities.Pickup")]
    public partial class Product {
        
        private string productDescriptionField;
        
        private string productNameField;
        
        private string[] subProductsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ProductDescription {
            get {
                return this.productDescriptionField;
            }
            set {
                this.productDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ProductName {
            get {
                return this.productNameField;
            }
            set {
                this.productNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] SubProducts {
            get {
                return this.subProductsField;
            }
            set {
                this.subProductsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SAPI.Entities.Pickup")]
    public partial class GetAllProductsAndSubProductsResponseEntity {
        
        private string errorMessageField;
        
        private bool isErrorField;
        
        private bool isErrorFieldSpecified;
        
        private Product[] productListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public bool IsError {
            get {
                return this.isErrorField;
            }
            set {
                this.isErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsErrorSpecified {
            get {
                return this.isErrorFieldSpecified;
            }
            set {
                this.isErrorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Product[] ProductList {
            get {
                return this.productListField;
            }
            set {
                this.productListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SAPI.Entities.Pickup")]
    public partial class CancelPickupResponseStatus {
        
        private string statusCodeField;
        
        private string statusInformationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StatusInformation {
            get {
                return this.statusInformationField;
            }
            set {
                this.statusInformationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SAPI.Entities.Pickup")]
    public partial class CancelPickupResponseEntity {
        
        private bool isErrorField;
        
        private bool isErrorFieldSpecified;
        
        private CancelPickupResponseStatus[] statusField;
        
        /// <remarks/>
        public bool IsError {
            get {
                return this.isErrorField;
            }
            set {
                this.isErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsErrorSpecified {
            get {
                return this.isErrorFieldSpecified;
            }
            set {
                this.isErrorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public CancelPickupResponseStatus[] Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SAPI.Entities.Pickup")]
    public partial class CancelPickupRequest {
        
        private System.DateTime pickupRegistrationDateField;
        
        private bool pickupRegistrationDateFieldSpecified;
        
        private string remarksField;
        
        private int tokenNumberField;
        
        private bool tokenNumberFieldSpecified;
        
        /// <remarks/>
        public System.DateTime PickupRegistrationDate {
            get {
                return this.pickupRegistrationDateField;
            }
            set {
                this.pickupRegistrationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PickupRegistrationDateSpecified {
            get {
                return this.pickupRegistrationDateFieldSpecified;
            }
            set {
                this.pickupRegistrationDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
            }
        }
        
        /// <remarks/>
        public int TokenNumber {
            get {
                return this.tokenNumberField;
            }
            set {
                this.tokenNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TokenNumberSpecified {
            get {
                return this.tokenNumberFieldSpecified;
            }
            set {
                this.tokenNumberFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SAPI.Entities.Pickup")]
    public partial class ResponseStatus {
        
        private PickupRegistrationStatus statusCodeField;
        
        private bool statusCodeFieldSpecified;
        
        private string statusInformationField;
        
        /// <remarks/>
        public PickupRegistrationStatus StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusCodeSpecified {
            get {
                return this.statusCodeFieldSpecified;
            }
            set {
                this.statusCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StatusInformation {
            get {
                return this.statusInformationField;
            }
            set {
                this.statusInformationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SAPI.Entities.Enums.Pickup")]
    public enum PickupRegistrationStatus {
        
        /// <remarks/>
        Valid,
        
        /// <remarks/>
        Invalid,
        
        /// <remarks/>
        InsertFailure,
        
        /// <remarks/>
        InsertSuccess,
        
        /// <remarks/>
        UpdateFailure,
        
        /// <remarks/>
        UpdateSuccess,
        
        /// <remarks/>
        DeleteFailure,
        
        /// <remarks/>
        DeleteSuccess,
        
        /// <remarks/>
        CancelSuccess,
        
        /// <remarks/>
        InvalidPickupSerialNo,
        
        /// <remarks/>
        InvalidClientName,
        
        /// <remarks/>
        InvalidPinCode,
        
        /// <remarks/>
        InvalidAddress1,
        
        /// <remarks/>
        InvalidAddress2,
        
        /// <remarks/>
        InvalidAddress3,
        
        /// <remarks/>
        InvalidPickupDays,
        
        /// <remarks/>
        InvalidPickupTime,
        
        /// <remarks/>
        InfoPickupDoesNotExist,
        
        /// <remarks/>
        InvalidOfficeCloseTime,
        
        /// <remarks/>
        InvalidOriginAreaCode,
        
        /// <remarks/>
        InvalidDestAreaCode,
        
        /// <remarks/>
        InvalidOriginScCode,
        
        /// <remarks/>
        InvalidDestScCode,
        
        /// <remarks/>
        InvalidOriginAreaCodeNotBlank,
        
        /// <remarks/>
        InvalidDestAreaCodeNotBlank,
        
        /// <remarks/>
        RegularDataTransfer,
        
        /// <remarks/>
        ServiceCentreCannotBeBlank,
        
        /// <remarks/>
        DestinationAreaNotInternational,
        
        /// <remarks/>
        ValueToLargeToCaculate,
        
        /// <remarks/>
        NoDataFoundException,
        
        /// <remarks/>
        UnauthorisedServiceCentre,
        
        /// <remarks/>
        InvalidLength,
        
        /// <remarks/>
        InvalidContactPersonName,
        
        /// <remarks/>
        InfoCustNotBelongsToServicesCenter,
        
        /// <remarks/>
        InvalidClientCode,
        
        /// <remarks/>
        InfoOffCreditedClient,
        
        /// <remarks/>
        InvalidClientCodeIsInvalid,
        
        /// <remarks/>
        OnlyRoute99Present,
        
        /// <remarks/>
        InfoPickupAlreadyExist,
        
        /// <remarks/>
        InvalidPickupForClientNotExist,
        
        /// <remarks/>
        InvalidPickupRouteCode,
        
        /// <remarks/>
        InvalidAreaCodeNotExists,
        
        /// <remarks/>
        InfoAraNotAdditionalLocation,
        
        /// <remarks/>
        InvalidServiceCentNotToArea,
        
        /// <remarks/>
        InvalidSCAndServiceCentNotToArea,
        
        /// <remarks/>
        InvalidAreaCode,
        
        /// <remarks/>
        HolidayAreaDoesNotExist,
        
        /// <remarks/>
        HolidayAreaExist,
        
        /// <remarks/>
        InvalidAreaScNotInRegion,
        
        /// <remarks/>
        InvalidServiceCenter,
        
        /// <remarks/>
        InfoCustNotSendImpExpShpt,
        
        /// <remarks/>
        InvalidOffCreditedClientNotAllowed,
        
        /// <remarks/>
        InfoCodifiedCashClient,
        
        /// <remarks/>
        InfoFreightCollectClient,
        
        /// <remarks/>
        InfoDartCollectClient,
        
        /// <remarks/>
        InvalidProductNotAllowForCentCust,
        
        /// <remarks/>
        InvalidCustNotSendCODShpt,
        
        /// <remarks/>
        InvalidCustNotSendFODShpt,
        
        /// <remarks/>
        InvalidCustNotSendTDDShpt,
        
        /// <remarks/>
        InvalidCustNotSendEDLShpt,
        
        /// <remarks/>
        InvalidCustomerCode,
        
        /// <remarks/>
        InvalidProductNotValidForCentBilllingCust,
        
        /// <remarks/>
        InvalidOrgAreaCustNotValidForCentBilllingCust,
        
        /// <remarks/>
        InvalidDestAreaCustNotValidForCentBilllingCust,
        
        /// <remarks/>
        InvalidCustForProductDTP,
        
        /// <remarks/>
        InvalidCustForProductIMP,
        
        /// <remarks/>
        InvalidCustForProductSII,
        
        /// <remarks/>
        InvalidCustForProductETAIL,
        
        /// <remarks/>
        InfoPickupAlreadyExistEnterAnother,
        
        /// <remarks/>
        InvalidPickupClient,
        
        /// <remarks/>
        InfoRegPickupCust,
        
        /// <remarks/>
        InfoFieldStaffSignOff,
        
        /// <remarks/>
        WarnCutoffTimeNotinPickup,
        
        /// <remarks/>
        InfoPUTime1CutOff,
        
        /// <remarks/>
        InfoPUTime2CutOff,
        
        /// <remarks/>
        InfoPUTime3CutOff,
        
        /// <remarks/>
        InfoPUTime4CutOff,
        
        /// <remarks/>
        InfoPUTime5CutOff,
        
        /// <remarks/>
        InvalidEmployeeCode,
        
        /// <remarks/>
        InvalidProductCode,
        
        /// <remarks/>
        InvalidProdNotForCust,
        
        /// <remarks/>
        InvalidStatusCode,
        
        /// <remarks/>
        InvalidTransactionCode,
        
        /// <remarks/>
        KeyCustomerCode,
        
        /// <remarks/>
        WarnLastCutoffTimeHandleWithCare,
        
        /// <remarks/>
        InfoFieldCutoffTimeSchedule,
        
        /// <remarks/>
        InvalidProductCodeNottoServiceCenter,
        
        /// <remarks/>
        CurrentTimeExceedsCutOffTime,
        
        /// <remarks/>
        EmbargoLocation,
        
        /// <remarks/>
        NonCompLocation,
        
        /// <remarks/>
        InvalidCountryCode,
        
        /// <remarks/>
        InvalidCityCode,
        
        /// <remarks/>
        LockFailed,
        
        /// <remarks/>
        UnlockFailed,
        
        /// <remarks/>
        InvalidCustomer,
        
        /// <remarks/>
        AreaCodeIsNull,
        
        /// <remarks/>
        CountryCodeIsNull,
        
        /// <remarks/>
        PickupDateIsNull,
        
        /// <remarks/>
        PickupTimeIsNull,
        
        /// <remarks/>
        OriginAreaCodeIsNullOrEmpty,
        
        /// <remarks/>
        DestinationAreaCodeIsNullOrEmpty,
        
        /// <remarks/>
        OriginServiceCenterIsNullOrEmpty,
        
        /// <remarks/>
        DestinationServiceCenterIsNullOrEmpty,
        
        /// <remarks/>
        ProductCodeIsNullOrEmpty,
        
        /// <remarks/>
        InvalidPickupDate,
        
        /// <remarks/>
        TDDServiceProvided,
        
        /// <remarks/>
        TDDServiceNotProvided,
        
        /// <remarks/>
        OriginCutOffTimeNotDefined,
        
        /// <remarks/>
        ClientNameIsNullorEmpty,
        
        /// <remarks/>
        ClientCodeIsNullorEmpty,
        
        /// <remarks/>
        RouteCodeIsNullorEmpty,
        
        /// <remarks/>
        PickSerialNumberIsnullorEmpty,
        
        /// <remarks/>
        AddressMandatoryIsNullorEmpty,
        
        /// <remarks/>
        PickUpTimeIsNullorEmpty,
        
        /// <remarks/>
        PickUpDaysIsNullorEmpty,
        
        /// <remarks/>
        CityCodeIsNullorEmpty,
        
        /// <remarks/>
        AreaCodeBelongsToMetro,
        
        /// <remarks/>
        OperationFailed,
        
        /// <remarks/>
        RequestAuthenticationFailed,
        
        /// <remarks/>
        CommunicationFailure,
        
        /// <remarks/>
        InvalidEmailId,
        
        /// <remarks/>
        InvalidTelePhone,
        
        /// <remarks/>
        InvalidMobile,
        
        /// <remarks/>
        InvalidActualWeight,
        
        /// <remarks/>
        InvalidVolumetric,
        
        /// <remarks/>
        InvalidNoOfPieces,
        
        /// <remarks/>
        EmptyCityBankCostCentre,
        
        /// <remarks/>
        InvalidRefNumberLengthExact,
        
        /// <remarks/>
        RefNoShouldBeAllNumericConfirm,
        
        /// <remarks/>
        InvalidRefNumberLengthRange,
        
        /// <remarks/>
        InvalidCityBankCostCenter,
        
        /// <remarks/>
        InvalidSubProductCode,
        
        /// <remarks/>
        CancelFailure,
        
        /// <remarks/>
        UnauthorizedUser,
        
        /// <remarks/>
        NullObject,
        
        /// <remarks/>
        BlankContactNo,
        
        /// <remarks/>
        InvalidVendorCode,
        
        /// <remarks/>
        OutBoundServiceNotAvailable,
        
        /// <remarks/>
        InvalidWaybillNumber,
        
        /// <remarks/>
        InvalidAwbno,
        
        /// <remarks/>
        PickupIsAlreadyRegister,
        
        /// <remarks/>
        ShipmentAlreadyPicked,
        
        /// <remarks/>
        kFileDataNotFound,
        
        /// <remarks/>
        AWBAlreadyManifested,
        
        /// <remarks/>
        CantReregisterCancelledPU,
        
        /// <remarks/>
        InvalidCustForDDN,
        
        /// <remarks/>
        InvalidSrcForDDN,
        
        /// <remarks/>
        InvalidCustNotSendEconomyShpt,
        
        /// <remarks/>
        PickupRegistrationNotAllowedforEmbargoLocation,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SAPI.Entities.Pickup")]
    public partial class PickupRegistrationResponse {
        
        private bool isErrorField;
        
        private bool isErrorFieldSpecified;
        
        private System.DateTime shipmentPickupDateField;
        
        private bool shipmentPickupDateFieldSpecified;
        
        private ResponseStatus[] statusField;
        
        private string tokenNumberField;
        
        /// <remarks/>
        public bool IsError {
            get {
                return this.isErrorField;
            }
            set {
                this.isErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsErrorSpecified {
            get {
                return this.isErrorFieldSpecified;
            }
            set {
                this.isErrorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ShipmentPickupDate {
            get {
                return this.shipmentPickupDateField;
            }
            set {
                this.shipmentPickupDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ShipmentPickupDateSpecified {
            get {
                return this.shipmentPickupDateFieldSpecified;
            }
            set {
                this.shipmentPickupDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public ResponseStatus[] Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TokenNumber {
            get {
                return this.tokenNumberField;
            }
            set {
                this.tokenNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SAPI.Entities.Admin")]
    public partial class UserProfile {
        
        private string api_typeField;
        
        private string areaField;
        
        private string customercodeField;
        
        private string isAdminField;
        
        private string licenceKeyField;
        
        private string loginIDField;
        
        private string passwordField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Api_type {
            get {
                return this.api_typeField;
            }
            set {
                this.api_typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Area {
            get {
                return this.areaField;
            }
            set {
                this.areaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Customercode {
            get {
                return this.customercodeField;
            }
            set {
                this.customercodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IsAdmin {
            get {
                return this.isAdminField;
            }
            set {
                this.isAdminField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LicenceKey {
            get {
                return this.licenceKeyField;
            }
            set {
                this.licenceKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LoginID {
            get {
                return this.loginIDField;
            }
            set {
                this.loginIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void RegisterPickupCompletedEventHandler(object sender, RegisterPickupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegisterPickupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegisterPickupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PickupRegistrationResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PickupRegistrationResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CancelPickupCompletedEventHandler(object sender, CancelPickupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CancelPickupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CancelPickupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CancelPickupResponseEntity Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CancelPickupResponseEntity)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetAllProductsAndSubProductsCompletedEventHandler(object sender, GetAllProductsAndSubProductsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllProductsAndSubProductsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllProductsAndSubProductsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetAllProductsAndSubProductsResponseEntity Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetAllProductsAndSubProductsResponseEntity)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591