//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationErrorLog
    {
        public int ID { get; set; }
        public string ErrorMessage { get; set; }
        public string ErrorSource { get; set; }
        public string HelpLink { get; set; }
        public string HResult { get; set; }
        public string StackTrace1 { get; set; }
        public string InnerExpMsg { get; set; }
        public string InnerExpSource { get; set; }
        public string StackTrace2 { get; set; }
        public string IPAddress { get; set; }
        public string AbsolutePathUrl { get; set; }
        public Nullable<System.DateTime> OccurredOn { get; set; }
        public string InsertedBy { get; set; }
    }
}
