//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class BarcodeStoneData
    {
        public int ID { get; set; }
        public string TagNo { get; set; }
        public string StoneType { get; set; }
        public decimal Rate { get; set; }
        public decimal Qty { get; set; }
    }
}
