//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHIT_CONNECTION_TABLE
    {
        public int ID { get; set; }
        public string Company_Code { get; set; }
        public string Branch_Code { get; set; }
        public string DatabaseName { get; set; }
        public string ChitServer { get; set; }
    }
}
