//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHTU_CHIT_CLOSURE
    {
        public string obj_id { get; set; }
        public string Scheme_Code { get; set; }
        public string Group_Code { get; set; }
        public int Chit_MembShipNo { get; set; }
        public decimal Amt_Received { get; set; }
        public decimal Bonus_Amt { get; set; }
        public decimal Interest_Percentage { get; set; }
        public decimal Interest_Amt { get; set; }
        public decimal Gift_Amount { get; set; }
        public decimal Deduction_Amt { get; set; }
        public string Closing_Mode { get; set; }
        public System.DateTime Closing_Date { get; set; }
        public string Bill_Number { get; set; }
        public Nullable<System.DateTime> Bill_Date { get; set; }
        public decimal Chit_Amt { get; set; }
        public string object_status { get; set; }
        public Nullable<decimal> total_wt_acc { get; set; }
        public Nullable<int> chit_trans_no { get; set; }
        public Nullable<decimal> win_amt { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public Nullable<System.DateTime> chq_issue_date { get; set; }
        public Nullable<int> chq_no { get; set; }
        public Nullable<int> acc_code { get; set; }
        public Nullable<decimal> Amt_Collected { get; set; }
        public string Closed_At { get; set; }
        public string Closed_By { get; set; }
        public string Old_Bill_Number { get; set; }
        public Nullable<bool> IsUpdated { get; set; }
        public Nullable<decimal> GrandTotal { get; set; }
        public Nullable<int> ClosureUniqId { get; set; }
        public Nullable<bool> isDormant { get; set; }
        public Nullable<decimal> scheme_discount_amt { get; set; }
        public Nullable<decimal> FixedGoldRate { get; set; }
    }
}
