//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerDocument
    {
        public int ID { get; set; }
        public int CustID { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
        public string ImagePath { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
