//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.CustomerDocuments = new HashSet<CustomerDocument>();
        }
    
        public int ID { get; set; }
        public string CustomerType { get; set; }
        public string Salutation { get; set; }
        public string Name { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PinCode { get; set; }
        public string MobileNo { get; set; }
        public string PhoneNo { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<System.DateTime> WeddingAnnivarsaryDate { get; set; }
        public string EmailID { get; set; }
        public Nullable<int> Age { get; set; }
        public string Sex { get; set; }
        public string GSTTIN { get; set; }
        public string LocalityID { get; set; }
        public Nullable<int> StateCode { get; set; }
        public string CountryCode { get; set; }
        public string CountryName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string ObjectStatus { get; set; }
        public string PrivilegeID { get; set; }
        public string CustCode { get; set; }
        public Nullable<decimal> CreditLimit { get; set; }
        public string CompanyCode { get; set; }
        public string BranchCode { get; set; }
        public int CustID { get; set; }
        public Nullable<long> ChitCardNo { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerDocument> CustomerDocuments { get; set; }
    }
}
