//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscountRuleConfiguration
    {
        public int ID { get; set; }
        public int OfferID { get; set; }
        public decimal FromWeight { get; set; }
        public decimal ToWeight { get; set; }
        public decimal MultiplesOf { get; set; }
        public decimal WtDiscountAmt { get; set; }
        public Nullable<int> NoOfCategories { get; set; }
        public Nullable<decimal> CatDiscountAmt { get; set; }
    }
}
