//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentCreationLog
    {
        public int ID { get; set; }
        public int ApplicationID { get; set; }
        public int TransTypeID { get; set; }
        public string CompanyCode { get; set; }
        public string BranchCode { get; set; }
        public string DocumentNo { get; set; }
        public System.DateTime DocumentDate { get; set; }
        public System.DateTime PostingDate { get; set; }
        public string OperatorCode { get; set; }
    }
}
