//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class EcomOrderAPILog
    {
        public int ID { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public string BranchOrderNo { get; set; }
        public string CentralRefNo { get; set; }
        public string Status { get; set; }
        public string Message { get; set; }
        public string Error { get; set; }
        public string RequestType { get; set; }
        public Nullable<System.DateTime> InsertedOn { get; set; }
    }
}
