//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSTComponent
    {
        public string Code { get; set; }
        public string Description { get; set; }
        public int CalculationOrder { get; set; }
        public bool IsInterstat { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public string branch_code { get; set; }
        public string company_code { get; set; }
        public Nullable<System.Guid> UniqRowID { get; set; }
        public string Status { get; set; }
    }
}
