//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSTLedgerEntry
    {
        public int EntryNo { get; set; }
        public string DocumentNo { get; set; }
        public int DocumentLineNo { get; set; }
        public System.DateTime PostingDate { get; set; }
        public int DocumentType { get; set; }
        public int TransactionType { get; set; }
        public string SourceType { get; set; }
        public string SourceNo { get; set; }
        public string ExternalDocNo { get; set; }
        public Nullable<int> GSTGroupType { get; set; }
        public string GSTComponentCode { get; set; }
        public string HSNSACCode { get; set; }
        public decimal GSTBaseAmount { get; set; }
        public decimal GSTPercent { get; set; }
        public decimal GSTAmount { get; set; }
        public string ItemCode { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> GrossWeight { get; set; }
        public Nullable<bool> IsGSTOnAdvanceAmt { get; set; }
        public Nullable<bool> IsReversed { get; set; }
        public Nullable<int> ReversedEntryNo { get; set; }
        public Nullable<int> ReversedByEntryNo { get; set; }
        public Nullable<bool> IstInterstate { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public string branch_code { get; set; }
        public string company_code { get; set; }
    }
}
