//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSTPostingSetup
    {
        public int ID { get; set; }
        public string GSTGroupCode { get; set; }
        public string GSTComponentCode { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public decimal GSTPercent { get; set; }
        public int CalculationOrder { get; set; }
        public Nullable<int> ReceivableAccount { get; set; }
        public Nullable<int> PayableAccount { get; set; }
        public Nullable<int> ExpenseAccount { get; set; }
        public Nullable<int> RefundAccount { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<bool> IsRegistered { get; set; }
        public string branch_code { get; set; }
        public string company_code { get; set; }
        public Nullable<System.Guid> UniqRowID { get; set; }
    }
}
