//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntegrationEnvironment
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public string HostUrl { get; set; }
        public string TokenEndPoint { get; set; }
        public string AuthToken { get; set; }
        public string RefreshToken { get; set; }
        public string AuthTokenPayload { get; set; }
        public string RefreshtokenPayload { get; set; }
        public Nullable<System.DateTime> AuthTokenExpiry { get; set; }
        public Nullable<System.DateTime> RefreshTokenExpiry { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
