//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM_MASTER
    {
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public string gs_code { get; set; }
        public string Item_code { get; set; }
        public string Item_Name { get; set; }
        public string Item { get; set; }
        public Nullable<int> Min_Units { get; set; }
        public string Tagged { get; set; }
        public string Karat { get; set; }
        public Nullable<decimal> Min_VA_ { get; set; }
        public string IsPiece { get; set; }
        public string stone { get; set; }
        public string diamond { get; set; }
        public string counter_code { get; set; }
        public string ischild { get; set; }
        public string hallmark { get; set; }
        public string certification { get; set; }
        public string obj_status { get; set; }
        public string Item_Category { get; set; }
        public string Item_Category_Name { get; set; }
        public string gs_Name { get; set; }
        public string GSTGoodsGroupCode { get; set; }
        public string GSTServicesGroupCode { get; set; }
        public string HSN { get; set; }
        public string CuttingPiece { get; set; }
    }
}
