//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KSTS_BARCODE_PORT_SETTINGS
    {
        public string obj_id { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public string com_port { get; set; }
        public int baud_rate { get; set; }
        public int data_bits { get; set; }
        public string parity { get; set; }
        public string stop_bits { get; set; }
        public string printer_port { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
    }
}
