//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KSTS_STATE_MASTER
    {
        public int id { get; set; }
        public string state_name { get; set; }
        public Nullable<int> tinno { get; set; }
        public string obj_status { get; set; }
    }
}
