//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KSTS_ACC_POSTING_SETUP
    {
        public int sno { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public string gs_code { get; set; }
        public string trans_type { get; set; }
        public int acc_code { get; set; }
    }
}
