//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KSTS_GS_ITEM_ENTRY
    {
        public string obj_id { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public int item_level1_id { get; set; }
        public string item_level1_name { get; set; }
        public string gs_code { get; set; }
        public string measure_type { get; set; }
        public string metal_type { get; set; }
        public string karat { get; set; }
        public string bill_type { get; set; }
        public decimal tax { get; set; }
        public int opening_units { get; set; }
        public decimal opening_gwt { get; set; }
        public decimal opening_nwt { get; set; }
        public decimal opening_gwt_value { get; set; }
        public decimal opening_nwt_value { get; set; }
        public string object_status { get; set; }
        public Nullable<int> display_order { get; set; }
        public string commodity_code { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public Nullable<decimal> excise_duty { get; set; }
        public Nullable<decimal> edu_cess { get; set; }
        public Nullable<decimal> high_ele { get; set; }
        public Nullable<decimal> tcs { get; set; }
        public string isStone { get; set; }
        public Nullable<decimal> purity { get; set; }
        public Nullable<decimal> tcs_perc { get; set; }
        public Nullable<decimal> S_tax { get; set; }
        public Nullable<decimal> I_tax { get; set; }
        public Nullable<decimal> C_tax { get; set; }
        public string GSTGoodsGroupCode { get; set; }
        public string GSTServicesGroupCode { get; set; }
        public string HSN { get; set; }
        public System.Guid UniqRowID { get; set; }
        public string PrintDescription { get; set; }
    }
}
