//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KSTS_ACC_CODE_MASTER
    {
        public int obj_id { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public int acc_code { get; set; }
        public string acc_name { get; set; }
        public Nullable<int> sub_group_id { get; set; }
        public string sub_group_name { get; set; }
        public Nullable<int> group_id { get; set; }
        public string group_name { get; set; }
        public string Description { get; set; }
        public string object_status { get; set; }
    }
}
