//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KSTS_MC_TYPES
    {
        public int obj_id { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public int mc_type_id { get; set; }
        public string mc_type_name { get; set; }
        public string wastage_percent { get; set; }
        public string mc_per_gram { get; set; }
        public string mc_amount { get; set; }
        public string wastage_grams { get; set; }
        public string va_percent { get; set; }
        public string mc_per_piece { get; set; }
        public string obj_status { get; set; }
        public Nullable<int> display_seq_no { get; set; }
    }
}
