//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KSTS_TDS_MASTER
    {
        public string obj_id { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public string tds_name { get; set; }
        public int tds_id { get; set; }
        public decimal tds { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string obj_status { get; set; }
        public Nullable<int> acc_code { get; set; }
        public Nullable<int> group_id { get; set; }
    }
}
