//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KSTS_ACC_GROUP_BALANCE
    {
        public string obj_id { get; set; }
        public int group_id { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public decimal opn_cr_bal { get; set; }
        public decimal opn_dr_bal { get; set; }
        public decimal opn_bal { get; set; }
        public string opn_bal_type { get; set; }
        public decimal dr_total { get; set; }
        public decimal cr_total { get; set; }
        public decimal net_total { get; set; }
        public decimal cls_cr_bal { get; set; }
        public decimal cls_dr_bal { get; set; }
        public decimal cls_bal { get; set; }
        public string cls_bal_type { get; set; }
        public decimal prv_fin_bal { get; set; }
        public decimal curr_fin_bal { get; set; }
        public decimal first_qtr_bal { get; set; }
        public decimal second_qtr_bal { get; set; }
        public decimal third_qtr_bal { get; set; }
        public decimal fourth_qtr_bal { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
    }
}
