//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KSTS_LOG_DETAILS
    {
        public int obj_id { get; set; }
        public string Description { get; set; }
        public System.DateTime date { get; set; }
        public string operator_code { get; set; }
        public string machine_name { get; set; }
        public Nullable<int> Fin_Year { get; set; }
        public string trans_type { get; set; }
    }
}
