//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KSTU_DIAMOND_MASTER
    {
        public string obj_id { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public int id { get; set; }
        public int dqty { get; set; }
        public decimal dcts { get; set; }
        public decimal rate { get; set; }
        public decimal amount { get; set; }
        public string color { get; set; }
        public string clarity { get; set; }
        public string certificate { get; set; }
        public string shape { get; set; }
        public string cut { get; set; }
        public string polish { get; set; }
        public string symmetry { get; set; }
        public string fluorescence { get; set; }
        public string obj_status { get; set; }
    }
}
