//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KSTU_ACC_EXCHANGE_ENTRY_DETAILS
    {
        public string obj_id { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public int exchange_no { get; set; }
        public int sno { get; set; }
        public System.DateTime exchange_date { get; set; }
        public string currency_type { get; set; }
        public decimal currency_value { get; set; }
        public decimal currency_rate { get; set; }
        public decimal Amount { get; set; }
        public string description { get; set; }
        public string referenceNo { get; set; }
        public Nullable<int> voucher_no { get; set; }
        public Nullable<int> cust_id { get; set; }
        public Nullable<int> invoice_no { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> invoice_date { get; set; }
        public Nullable<int> fin_year { get; set; }
        public string obj_status { get; set; }
        public string isFixed { get; set; }
        public string bill_no { get; set; }
        public string cflag { get; set; }
    }
}
