//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KSTU_WS_CUSTOMER_TOUCH_MASTER
    {
        public string obj_id { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public int cust_id { get; set; }
        public decimal touch_filter { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string gs_code { get; set; }
        public string item_code { get; set; }
        public string cust_name { get; set; }
        public Nullable<int> sno { get; set; }
        public string stone_charges_type { get; set; }
    }
}
