//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KSTU_ACC_CLOSING
    {
        public string obj_id { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public int fin_year { get; set; }
        public string gs_name { get; set; }
        public decimal avg_rate { get; set; }
        public decimal closing_wt { get; set; }
        public decimal closing_value { get; set; }
        public Nullable<int> pcs { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string gs_code { get; set; }
        public System.Guid UniqRowID { get; set; }
    }
}
