//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KSTU_GRADE_MASTER
    {
        public string obj_id { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public string grade { get; set; }
        public Nullable<decimal> mc_per_gram { get; set; }
        public Nullable<decimal> wast_percentage { get; set; }
        public Nullable<decimal> mc_amount { get; set; }
        public Nullable<decimal> wastage_grms { get; set; }
        public Nullable<decimal> mc_percent { get; set; }
        public string mc_type { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
    }
}
