//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KSTU_COMPANY_MASTER
    {
        public string obj_id { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public string company_name { get; set; }
        public string short_name { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string address3 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string phone_no { get; set; }
        public string mobile_no { get; set; }
        public string fax_no { get; set; }
        public string pin_code { get; set; }
        public string pan_no { get; set; }
        public string tin_no { get; set; }
        public string cst_no { get; set; }
        public string email_id { get; set; }
        public string website { get; set; }
        public string company_footer { get; set; }
        public Nullable<int> display_no { get; set; }
        public string object_status { get; set; }
        public string branch_name { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string HOCODE { get; set; }
        public string ED_Reg_No { get; set; }
        public string Header1 { get; set; }
        public string Header2 { get; set; }
        public string Header3 { get; set; }
        public string Header4 { get; set; }
        public string Header5 { get; set; }
        public string Header6 { get; set; }
        public string Header7 { get; set; }
        public string Footer1 { get; set; }
        public string Footer2 { get; set; }
        public string Currency_code { get; set; }
        public string Country_name { get; set; }
        public string default_currency_code { get; set; }
        public Nullable<int> state_code { get; set; }
        public Nullable<int> store_location_id { get; set; }
    }
}
