//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KSTU_ITEM_LIST_GROUP_MASTER
    {
        public string obj_id { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public int item_level1_id { get; set; }
        public string item_level1_name { get; set; }
        public string gs_code { get; set; }
        public int item_level2_id { get; set; }
        public string item_level2_name { get; set; }
        public int item_level3_id { get; set; }
        public string item_level3_name { get; set; }
        public int item_level4_id { get; set; }
        public string item_level4_name { get; set; }
        public int item_level5_id { get; set; }
        public string item_level5_name { get; set; }
        public Nullable<int> item_level6_id { get; set; }
        public string item_level6_name { get; set; }
        public string short_description { get; set; }
        public string ischild { get; set; }
        public Nullable<int> min_units { get; set; }
        public Nullable<decimal> min_stock_level { get; set; }
        public string catalogId { get; set; }
        public string grade { get; set; }
        public string tagged { get; set; }
        public string stone { get; set; }
        public string diamond { get; set; }
        public string counter_code { get; set; }
        public string karat { get; set; }
        public string piece_item { get; set; }
        public string obj_status { get; set; }
        public string alias_name { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public Nullable<decimal> min_profit_percent { get; set; }
        public string QTY_LOCK { get; set; }
        public string hallmark { get; set; }
        public string certification { get; set; }
        public Nullable<decimal> tcs_perc { get; set; }
        public string GSTGoodsGroupCode { get; set; }
        public string GSTServicesGroupCode { get; set; }
        public string HSN { get; set; }
        public System.Guid UniqRowID { get; set; }
        public string CuttingPiece { get; set; }
    }
}
