//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KSTU_ITEM_ENTRY_MASTER
    {
        public string obj_id { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public string product_code { get; set; }
        public string item_name { get; set; }
        public string bill_type { get; set; }
        public int min_units { get; set; }
        public string karats { get; set; }
        public decimal min_stock_level { get; set; }
        public string catalogId { get; set; }
        public decimal min_va { get; set; }
        public decimal max_va { get; set; }
        public string obj_status { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public Nullable<decimal> tcs_perc { get; set; }
    }
}
