//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KSTU_ORDER_RATE_MASTER
    {
        public int Id { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public string booking_name { get; set; }
        public string description { get; set; }
        public decimal adv_amount_per { get; set; }
        public int fixed_days { get; set; }
        public string cflag { get; set; }
        public string operator_code { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public Nullable<decimal> min_weight { get; set; }
    }
}
