//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KSTU_TCS_MASTER
    {
        public string obj_id { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public string is_withKYC { get; set; }
        public decimal amount_limt { get; set; }
        public decimal tcs_percent { get; set; }
        public int acc_code { get; set; }
        public string acc_name { get; set; }
        public string calculated_on { get; set; }
        public Nullable<System.DateTime> effective_date { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string transaction_type { get; set; }
        public string is_tds { get; set; }
    }
}
