//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KSTU_ACC_GROUP_MASTER
    {
        public string obj_id { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public int group_id { get; set; }
        public string group_name { get; set; }
        public string group_type { get; set; }
        public string group_description { get; set; }
        public string is_trading { get; set; }
        public string obj_status { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public Nullable<int> parent_group_id { get; set; }
        public System.Guid UniqRowID { get; set; }
        public string NewGroupCode { get; set; }
        public string NewSubGroupCode { get; set; }
    }
}
