//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KSTU_ACC_VOUCHER_TRANSACTIONS
    {
        public string obj_id { get; set; }
        public string branch_code { get; set; }
        public string company_code { get; set; }
        public int txt_seq_no { get; set; }
        public int voucher_no { get; set; }
        public int voucher_seq_no { get; set; }
        public string acc_type { get; set; }
        public System.DateTime voucher_date { get; set; }
        public int acc_code { get; set; }
        public decimal dr_amount { get; set; }
        public decimal cr_amount { get; set; }
        public string chq_no { get; set; }
        public System.DateTime chq_date { get; set; }
        public int fin_year { get; set; }
        public int fin_period { get; set; }
        public int acc_code_master { get; set; }
        public string narration { get; set; }
        public int contra_seq_no { get; set; }
        public string reconsile_flag { get; set; }
        public System.DateTime reconsile_date { get; set; }
        public string receipt_no { get; set; }
        public string trans_type { get; set; }
        public System.DateTime inserted_on { get; set; }
        public string cflag { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string approved_by { get; set; }
        public Nullable<System.DateTime> approved_date { get; set; }
        public string is_approved { get; set; }
        public Nullable<int> subledger_acc_code { get; set; }
        public string party_name { get; set; }
        public string Cancelled_by { get; set; }
        public string Cancelled_remarks { get; set; }
        public string voucher_type { get; set; }
        public string reconsile_by { get; set; }
        public string currency_type { get; set; }
        public int New_voucher_no { get; set; }
        public string section_id { get; set; }
        public string is_tds { get; set; }
        public Nullable<decimal> TDS_amount { get; set; }
        public string Is_Verified { get; set; }
        public string Verified_By { get; set; }
        public Nullable<System.DateTime> Verified_Date { get; set; }
        public string Verified_Remarks { get; set; }
        public string Is_Authorized { get; set; }
        public string Authorized_By { get; set; }
        public Nullable<System.DateTime> Authorized_Date { get; set; }
        public string Authorized_Remarks { get; set; }
        public Nullable<decimal> exchange_rate { get; set; }
        public Nullable<decimal> currency_value { get; set; }
        public System.Guid UniqRowID { get; set; }
        public string pay_mode { get; set; }
        public Nullable<System.DateTime> cancelled_date { get; set; }
        public string isreversed { get; set; }
    }
}
