//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KSTU_SUPPLIER_OPN_DETAILS
    {
        public string obj_id { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public string party_code { get; set; }
        public string metal_code { get; set; }
        public string weight_type { get; set; }
        public decimal opn_weight { get; set; }
        public string bal_type { get; set; }
        public decimal opn_bal { get; set; }
        public string obj_status { get; set; }
        public System.DateTime UpdateOn { get; set; }
        public string voucher_code { get; set; }
        public Nullable<decimal> opn_pure_weight { get; set; }
        public Nullable<decimal> opn_net_weight { get; set; }
        public Nullable<int> Fin_Year { get; set; }
        public string gs_code { get; set; }
        public Nullable<int> ref_no { get; set; }
        public System.Guid UniqRowID { get; set; }
    }
}
