//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KSTU_CHARGES_MASTER
    {
        public string obj_id { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public string charge_name { get; set; }
        public decimal from_wt { get; set; }
        public decimal to_wt { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string obj_status { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
    }
}
