//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KSTU_VA_MASTER
    {
        public string obj_id { get; set; }
        public int sno { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public string gs_code { get; set; }
        public string category_code { get; set; }
        public Nullable<decimal> from_wt { get; set; }
        public Nullable<decimal> to_wt { get; set; }
        public Nullable<decimal> mc_amount { get; set; }
        public Nullable<decimal> mc_per_gram { get; set; }
        public Nullable<decimal> wastage_grms { get; set; }
        public Nullable<decimal> wast_percentage { get; set; }
        public string type_id { get; set; }
        public Nullable<decimal> range { get; set; }
        public Nullable<decimal> mc_percent { get; set; }
        public string party_code { get; set; }
        public string design_code { get; set; }
        public string obj_status { get; set; }
        public Nullable<decimal> mc_per_piece { get; set; }
        public Nullable<decimal> valueadded { get; set; }
    }
}
