//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KSTU_CUSTOMER_MASTER
    {
        public string obj_id { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public int cust_id { get; set; }
        public string cust_name { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string address3 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string pin_code { get; set; }
        public string mobile_no { get; set; }
        public string phone_no { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public Nullable<System.DateTime> wedding_date { get; set; }
        public string customer_type { get; set; }
        public string object_status { get; set; }
        public string spouse_name { get; set; }
        public string child_name1 { get; set; }
        public string child_name2 { get; set; }
        public string child_name3 { get; set; }
        public Nullable<System.DateTime> spouse_dob { get; set; }
        public Nullable<System.DateTime> child1_dob { get; set; }
        public Nullable<System.DateTime> child2_dob { get; set; }
        public Nullable<System.DateTime> child3_dob { get; set; }
        public string pan_no { get; set; }
        public string id_type { get; set; }
        public string id_details { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string Email_ID { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string salutation { get; set; }
        public string country_code { get; set; }
        public string loyality_id { get; set; }
        public string ic_no { get; set; }
        public string passport_no { get; set; }
        public string pr_no { get; set; }
        public string privilege_id { get; set; }
        public Nullable<int> age { get; set; }
        public string Country_name { get; set; }
        public string cust_code { get; set; }
        public Nullable<decimal> cust_credit_limit { get; set; }
        public string tin { get; set; }
        public Nullable<int> state_code { get; set; }
        public System.Guid UniqRowID { get; set; }
        public string Corparate_ID { get; set; }
        public string Corporate_Branch_ID { get; set; }
        public string Employee_Id { get; set; }
        public string Registered_MN { get; set; }
        public string profession_ID { get; set; }
        public string Empcorp_Email_ID { get; set; }
        public string imageid_path { get; set; }
        public string corp_imageid_path { get; set; }
        public string imageid_path2 { get; set; }
        public Nullable<int> RepoCustId { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string AccHolderName { get; set; }
        public string Accsalutation { get; set; }
        public string religion { get; set; }
        public string CRM_ID { get; set; }
    }
}
