//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KSTU_ACC_CHEQUE_MASTER
    {
        public string obj_id { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public int acc_code { get; set; }
        public int chq_no { get; set; }
        public int no_of_chqs { get; set; }
        public int chq_start_no { get; set; }
        public int chq_end_no { get; set; }
        public System.DateTime chq_issue_date { get; set; }
        public string chq_issued { get; set; }
        public string chq_closed { get; set; }
        public string chq_closed_by { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string chq_closed_remarks { get; set; }
        public Nullable<decimal> Max_amount { get; set; }
        public System.Guid UniqRowID { get; set; }
    }
}
