//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KSTU_STONE_DIAMOND_MASTER
    {
        public string obj_id { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public string type { get; set; }
        public string stone_types { get; set; }
        public string stone_name { get; set; }
        public string counter_code { get; set; }
        public string brand_name { get; set; }
        public string color { get; set; }
        public string cut { get; set; }
        public string clarity { get; set; }
        public string obj_status { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string code { get; set; }
        public string batch { get; set; }
        public string uom { get; set; }
        public string HSN { get; set; }
        public Nullable<decimal> stone_value { get; set; }
        public System.Guid UniqRowID { get; set; }
        public string GSTGroupCode { get; set; }
        public string old_stone_name { get; set; }
    }
}
