//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KSTU_DIAMOND_RATE_MASTER
    {
        public string obj_id { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public string dm_name { get; set; }
        public int Slno { get; set; }
        public decimal karat_from { get; set; }
        public decimal karat_to { get; set; }
        public decimal rate { get; set; }
        public string object_status { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string uom { get; set; }
        public string color { get; set; }
        public string clarity { get; set; }
        public string shape { get; set; }
        public string cut { get; set; }
        public string polish { get; set; }
        public string symmetry { get; set; }
        public string fluorescence { get; set; }
        public string certificate { get; set; }
        public System.Guid UniqRowID { get; set; }
        public Nullable<decimal> MinAmt { get; set; }
        public string Size { get; set; }
    }
}
