//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KSTU_MIN_STOCK_MASTER
    {
        public string obj_id { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public string gs_code { get; set; }
        public string category_code { get; set; }
        public string category_name { get; set; }
        public string design_code { get; set; }
        public string design_name { get; set; }
        public string counter_code { get; set; }
        public string counter_name { get; set; }
        public int min_qty { get; set; }
        public decimal min_wt { get; set; }
        public Nullable<int> max_qty { get; set; }
        public Nullable<decimal> max_wt { get; set; }
        public string is_saved { get; set; }
        public Nullable<System.DateTime> updated_on { get; set; }
        public Nullable<System.Guid> UniqRowID { get; set; }
    }
}
