//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KSTU_DISCOUNT_ITEM_CATEGORY_GROUPING
    {
        public string obj_id { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public int offer_id { get; set; }
        public string catagory_code { get; set; }
        public string gs_code { get; set; }
        public string Item_code { get; set; }
        public string counter_code { get; set; }
    }
}
