//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KSTU_SUPPLIER_MASTER
    {
        public string obj_id { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public string party_code { get; set; }
        public string party_name { get; set; }
        public string voucher_code { get; set; }
        public string e_mail { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string address3 { get; set; }
        public string district { get; set; }
        public string state { get; set; }
        public string state_status { get; set; }
        public string city { get; set; }
        public string country { get; set; }
        public string pincode { get; set; }
        public string phone { get; set; }
        public string mobile { get; set; }
        public string FaxNo { get; set; }
        public string pan_no { get; set; }
        public string website { get; set; }
        public string TIN { get; set; }
        public string TDS { get; set; }
        public string VAT { get; set; }
        public string cst_no { get; set; }
        public string obj_status { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string Party_RTGScode { get; set; }
        public string Party_NEFTcode { get; set; }
        public string Party_IFSCcode { get; set; }
        public string Party_AC_No { get; set; }
        public string Party_MICR_No { get; set; }
        public string Party_BankName { get; set; }
        public string Party_BankBranch { get; set; }
        public string Party_BankAddress { get; set; }
        public string Contact_Person { get; set; }
        public string Contact_Email { get; set; }
        public string Contact_MobileNo { get; set; }
        public string Party_AC_Name { get; set; }
        public Nullable<decimal> opn_bal { get; set; }
        public string opn_bal_type { get; set; }
        public Nullable<decimal> opn_wt { get; set; }
        public string opn_wt_type { get; set; }
        public Nullable<int> credit_period { get; set; }
        public Nullable<int> lead_time { get; set; }
        public Nullable<decimal> max_payment { get; set; }
        public Nullable<decimal> conv_rate { get; set; }
        public string swift_code { get; set; }
        public string branch_type { get; set; }
        public Nullable<decimal> tds_percent { get; set; }
        public Nullable<decimal> credit_weight { get; set; }
        public int tds_id { get; set; }
        public string isSameEntity { get; set; }
        public Nullable<int> state_code { get; set; }
        public System.Guid UniqRowID { get; set; }
        public string schemetype { get; set; }
        public string supplierMetal { get; set; }
    }
}
