//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KSTU_ACC_FY_MASTER
    {
        public string obj_id { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public int fin_year { get; set; }
        public string fin_period { get; set; }
        public System.DateTime fin_year_start { get; set; }
        public System.DateTime fin_year_end { get; set; }
        public int fin_seq_no { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
    }
}
