//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KSTU_ACC_VCH_TRANS_HISTORY
    {
        public int uniqid { get; set; }
        public string obj_id { get; set; }
        public string branch_code { get; set; }
        public string company_code { get; set; }
        public int txt_seq_no { get; set; }
        public int voucher_no { get; set; }
        public int voucher_seq_no { get; set; }
        public string acc_type { get; set; }
        public System.DateTime voucher_date { get; set; }
        public int acc_code { get; set; }
        public decimal dr_amount { get; set; }
        public decimal cr_amount { get; set; }
        public string chq_no { get; set; }
        public System.DateTime chq_date { get; set; }
        public int fin_year { get; set; }
        public int fin_period { get; set; }
        public int acc_code_master { get; set; }
        public string narration { get; set; }
        public int contra_seq_no { get; set; }
        public string reconsile_flag { get; set; }
        public System.DateTime reconsile_date { get; set; }
        public string receipt_no { get; set; }
        public string trans_type { get; set; }
        public string action_type { get; set; }
        public System.DateTime action_on { get; set; }
        public string action_by { get; set; }
        public Nullable<System.DateTime> inserted_on { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string approved_by { get; set; }
        public Nullable<System.DateTime> approved_date { get; set; }
        public string is_approved { get; set; }
        public Nullable<int> subledger_acc_code { get; set; }
        public string party_name { get; set; }
        public string Cancelled_by { get; set; }
        public string Cancelled_remarks { get; set; }
        public string voucher_type { get; set; }
        public string reconsile_by { get; set; }
        public string currency_type { get; set; }
    }
}
