//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KTTS_CARD_COMMISSION
    {
        public string obj_id { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public string bank { get; set; }
        public decimal charge { get; set; }
        public decimal service_tax { get; set; }
        public int acc_code { get; set; }
        public int bank_acc_code { get; set; }
        public Nullable<int> disp_seq { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public Nullable<decimal> CustCharge { get; set; }
    }
}
