//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KTTU_GS_SALES_STOCK
    {
        public string obj_id { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public System.DateTime date { get; set; }
        public string item_name { get; set; }
        public string gs_code { get; set; }
        public int opening_units { get; set; }
        public decimal opening_gwt { get; set; }
        public decimal opening_nwt { get; set; }
        public int receipt_units { get; set; }
        public decimal receipt_gwt { get; set; }
        public decimal receipt_nwt { get; set; }
        public int issue_units { get; set; }
        public decimal issue_gwt { get; set; }
        public decimal issue_nwt { get; set; }
        public int closing_units { get; set; }
        public decimal closing_gwt { get; set; }
        public decimal closing_nwt { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
    }
}
