//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KTTU_ORDER_PRODUCTION_ISSUE_STONE_DETAILS
    {
        public string obj_id { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public int issue_no { get; set; }
        public int order_no { get; set; }
        public int order_slno { get; set; }
        public int stn_slno { get; set; }
        public string type { get; set; }
        public string stn_name { get; set; }
        public int stn_qty { get; set; }
        public decimal stn_carat { get; set; }
        public decimal stn_weight { get; set; }
        public decimal stn_rate { get; set; }
        public decimal stn_amount { get; set; }
        public Nullable<int> Fin_year { get; set; }
    }
}
