//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KTTU_OFFER_DISCOUNT_DETAILS
    {
        public string obj_id { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public Nullable<int> slno { get; set; }
        public string offer_type { get; set; }
        public string gs_code { get; set; }
        public string counter_code { get; set; }
        public string item_name { get; set; }
        public decimal from_weight { get; set; }
        public decimal to_weight { get; set; }
        public decimal from_carrat { get; set; }
        public decimal to_carrat { get; set; }
        public decimal from_amount { get; set; }
        public decimal to_amount { get; set; }
        public Nullable<int> lesser_age { get; set; }
        public Nullable<int> greater_age { get; set; }
        public decimal offer_per_grm { get; set; }
        public decimal offer_per_carrat { get; set; }
        public decimal Diamond_value_percentage { get; set; }
        public decimal Stone_value_percentage { get; set; }
        public decimal VA_percentage { get; set; }
        public decimal itemtotal_percentage { get; set; }
        public decimal freeGoldvalue_per_grm { get; set; }
        public string isActive { get; set; }
        public string Offer_ID { get; set; }
    }
}
