//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KTTU_SALES_STOCK_DETAILS
    {
        public string obj_id { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public int transfer_no { get; set; }
        public int sl_no { get; set; }
        public string item_name { get; set; }
        public int qty { get; set; }
        public decimal gwt { get; set; }
        public decimal swt { get; set; }
        public decimal nwt { get; set; }
        public decimal amount { get; set; }
        public string gs_code { get; set; }
        public Nullable<int> Fin_Year { get; set; }
        public Nullable<decimal> Dcts { get; set; }
        public string barcode_no { get; set; }
    }
}
