//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KTTU_TDS_EXPENSE_DETAILS
    {
        public string obj_id { get; set; }
        public int expense_no { get; set; }
        public System.DateTime expense_date { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public string suppliercode { get; set; }
        public string suppliername { get; set; }
        public int sno { get; set; }
        public int acc_code { get; set; }
        public string acc_name { get; set; }
        public string invoiceno { get; set; }
        public System.DateTime invoicedate { get; set; }
        public decimal amount { get; set; }
        public string tax_name { get; set; }
        public decimal tax_percntage { get; set; }
        public decimal tax_amount { get; set; }
        public decimal total_amount { get; set; }
        public decimal tds_precentage { get; set; }
        public decimal tds_amount { get; set; }
        public string cflag { get; set; }
        public string cancelled_by { get; set; }
        public string operator_code { get; set; }
        public string description { get; set; }
        public string obj_status { get; set; }
        public Nullable<decimal> SGST_Percent { get; set; }
        public Nullable<decimal> SGST_Amount { get; set; }
        public Nullable<decimal> CGST_Percent { get; set; }
        public Nullable<decimal> CGST_Amount { get; set; }
        public Nullable<decimal> IGST_Percent { get; set; }
        public Nullable<decimal> IGST_Amount { get; set; }
        public string HSN { get; set; }
        public string GSTGroupCode { get; set; }
        public string acc_type { get; set; }
        public Nullable<int> chq_no { get; set; }
        public Nullable<System.DateTime> chq_date { get; set; }
        public string GST_No { get; set; }
        public string Other_Party_Name { get; set; }
        public string party_code { get; set; }
        public Nullable<decimal> CESS_Percent { get; set; }
        public Nullable<decimal> CESS_Amount { get; set; }
        public string remarks { get; set; }
        public string PAN_No { get; set; }
        public string IsEligible { get; set; }
        public string hsnDescription { get; set; }
        public Nullable<decimal> roundoff { get; set; }
        public Nullable<decimal> final_Amount { get; set; }
        public string PONumber { get; set; }
        public Nullable<System.Guid> UniqRowID { get; set; }
        public string RefNumber { get; set; }
        public string Cancelled_remarks { get; set; }
        public Nullable<System.DateTime> cancelled_date { get; set; }
        public string Cost_center { get; set; }
    }
}
