//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KTTU_SALES_EST_DETAILS
    {
        public string obj_id { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public int est_no { get; set; }
        public int sl_no { get; set; }
        public Nullable<int> bill_no { get; set; }
        public string barcode_no { get; set; }
        public string sal_code { get; set; }
        public string counter_code { get; set; }
        public string item_name { get; set; }
        public int item_no { get; set; }
        public decimal gwt { get; set; }
        public decimal swt { get; set; }
        public decimal nwt { get; set; }
        public Nullable<decimal> AddWt { get; set; }
        public Nullable<decimal> DeductWt { get; set; }
        public decimal making_charge_per_rs { get; set; }
        public decimal wast_percent { get; set; }
        public decimal gold_value { get; set; }
        public decimal va_amount { get; set; }
        public decimal stone_charges { get; set; }
        public Nullable<decimal> diamond_charges { get; set; }
        public decimal total_amount { get; set; }
        public Nullable<decimal> hallmarcharges { get; set; }
        public Nullable<decimal> mc_amount { get; set; }
        public Nullable<decimal> wastage_grms { get; set; }
        public Nullable<decimal> mc_percent { get; set; }
        public Nullable<int> Addqty { get; set; }
        public Nullable<int> Deductqty { get; set; }
        public Nullable<decimal> offer_value { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string gs_code { get; set; }
        public Nullable<decimal> rate { get; set; }
        public string karat { get; set; }
        public string ad_barcode { get; set; }
        public string ad_counter { get; set; }
        public string ad_item { get; set; }
        public string isEDApplicable { get; set; }
        public Nullable<int> mc_type { get; set; }
        public Nullable<int> Fin_Year { get; set; }
        public string New_Bill_No { get; set; }
        public Nullable<decimal> item_total_after_discount { get; set; }
        public Nullable<decimal> item_additional_discount { get; set; }
        public Nullable<decimal> tax_percentage { get; set; }
        public Nullable<decimal> tax_amount { get; set; }
        public Nullable<decimal> item_final_amount { get; set; }
        public string supplier_code { get; set; }
        public string item_size { get; set; }
        public string img_id { get; set; }
        public string design_code { get; set; }
        public string design_name { get; set; }
        public string batch_id { get; set; }
        public string rf_id { get; set; }
        public Nullable<decimal> mc_per_piece { get; set; }
        public Nullable<decimal> Discount_Mc { get; set; }
        public Nullable<decimal> Total_sales_mc { get; set; }
        public Nullable<decimal> Mc_Discount_Amt { get; set; }
        public Nullable<decimal> purchase_mc { get; set; }
        public string GSTGroupCode { get; set; }
        public Nullable<decimal> SGST_Percent { get; set; }
        public Nullable<decimal> SGST_Amount { get; set; }
        public Nullable<decimal> CGST_Percent { get; set; }
        public Nullable<decimal> CGST_Amount { get; set; }
        public Nullable<decimal> IGST_Percent { get; set; }
        public Nullable<decimal> IGST_Amount { get; set; }
        public string HSN { get; set; }
        public string Piece_Rate { get; set; }
        public Nullable<decimal> DeductSWt { get; set; }
        public Nullable<decimal> Ord_Discount_Amt { get; set; }
        public string ded_counter { get; set; }
        public string ded_item { get; set; }
        public Nullable<decimal> CESSPercent { get; set; }
        public Nullable<decimal> CESSAmount { get; set; }
        public Nullable<int> gridslno { get; set; }
        public Nullable<decimal> vaporLoss { get; set; }
        public Nullable<decimal> vaporAmount { get; set; }
        public Nullable<decimal> DiscountVoucherAmt { get; set; }
        public Nullable<decimal> OfferRatePerGram { get; set; }
        public Nullable<decimal> SchemeDiscountAmount { get; set; }
        public Nullable<decimal> SchemeWeightAdjusted { get; set; }
    }
}
