//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KTTU_SALES_MASTER_OLD
    {
        public string obj_id { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public int bill_no { get; set; }
        public int est_no { get; set; }
        public Nullable<int> cust_Id { get; set; }
        public string cust_name { get; set; }
        public int order_no { get; set; }
        public System.DateTime order_date { get; set; }
        public decimal order_amount { get; set; }
        public System.DateTime bill_date { get; set; }
        public string operator_code { get; set; }
        public string karat { get; set; }
        public Nullable<decimal> rate { get; set; }
        public decimal tax { get; set; }
        public Nullable<decimal> cess_tax { get; set; }
        public Nullable<decimal> discount_amount { get; set; }
        public Nullable<decimal> total_cess_amount { get; set; }
        public Nullable<decimal> total_tax_amount { get; set; }
        public decimal total_bill_amount { get; set; }
        public Nullable<decimal> grand_total { get; set; }
        public Nullable<decimal> purchase_amount { get; set; }
        public Nullable<decimal> spurchase_amount { get; set; }
        public string s_type { get; set; }
        public string cflag { get; set; }
        public string cancelled_by { get; set; }
        public string discount_autharity { get; set; }
        public Nullable<int> purchase_no { get; set; }
        public Nullable<int> spurchase_no { get; set; }
        public string gstype { get; set; }
        public string iscredit { get; set; }
        public string bill_counter { get; set; }
        public string is_ins { get; set; }
        public string remarks { get; set; }
        public string guranteename { get; set; }
        public Nullable<System.DateTime> duedate { get; set; }
        public Nullable<decimal> balance_amt { get; set; }
        public string new_cust { get; set; }
        public Nullable<int> SalesbillPK { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string item_set { get; set; }
        public Nullable<decimal> total_sale_amount { get; set; }
        public Nullable<decimal> round_off { get; set; }
        public Nullable<decimal> ed_cess { get; set; }
        public Nullable<decimal> hed_cess { get; set; }
        public Nullable<decimal> ed_cess_percent { get; set; }
        public Nullable<decimal> hed_cess_percent { get; set; }
        public Nullable<decimal> excise_duty_percent { get; set; }
        public Nullable<decimal> excise_duty_amount { get; set; }
        public Nullable<int> fin_year { get; set; }
        public string cancelled_remarks { get; set; }
        public Nullable<decimal> hi_scheme_amount { get; set; }
        public Nullable<int> hi_scheme_no { get; set; }
        public Nullable<decimal> hi_bonus_amount { get; set; }
        public string New_Bill_No { get; set; }
        public string U_obj_id { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string address3 { get; set; }
        public string city { get; set; }
        public string pin_code { get; set; }
        public string mobile_no { get; set; }
        public string state { get; set; }
        public Nullable<int> state_code { get; set; }
        public string tin { get; set; }
        public string pan_no { get; set; }
        public string manger_Code { get; set; }
    }
}
