//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KTTU_TRAN_MODI_LOG
    {
        public int txt_id { get; set; }
        public string doc_type { get; set; }
        public string doc_no { get; set; }
        public System.DateTime doc_date { get; set; }
        public string doc_description { get; set; }
        public string doc_remarks { get; set; }
        public string operator_code { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
    }
}
