//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KTTU_BARCODE_STONE_DETAILS
    {
        public string obj_id { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public int sl_no { get; set; }
        public string barcode_no { get; set; }
        public string type { get; set; }
        public string name { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<decimal> carrat { get; set; }
        public Nullable<decimal> rate { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string clarity { get; set; }
        public string color { get; set; }
        public string prod_ida { get; set; }
        public string prod_tagno { get; set; }
        public string old_barcode_no { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string stone_type { get; set; }
        public string stone_gs_type { get; set; }
        public Nullable<int> Fin_Year { get; set; }
        public string uom { get; set; }
        public Nullable<decimal> pur_cost { get; set; }
        public string stone_code { get; set; }
        public string shape { get; set; }
        public string cut { get; set; }
        public string polish { get; set; }
        public string symmetry { get; set; }
        public string fluorescence { get; set; }
        public string certificate { get; set; }
        public System.Guid UniqRowID { get; set; }
        public Nullable<decimal> pur_rate { get; set; }
        public string Size { get; set; }
        public string Certification_no { get; set; }
    }
}
