//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KTTU_SALES_EST_MASTER
    {
        public string obj_id { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public int est_no { get; set; }
        public int order_no { get; set; }
        public int Cust_Id { get; set; }
        public string Cust_Name { get; set; }
        public System.DateTime order_date { get; set; }
        public System.DateTime est_date { get; set; }
        public string operator_code { get; set; }
        public string karat { get; set; }
        public decimal rate { get; set; }
        public decimal tax { get; set; }
        public decimal total_tax_amount { get; set; }
        public decimal total_est_amount { get; set; }
        public decimal grand_total { get; set; }
        public decimal order_amount { get; set; }
        public decimal purchase_amount { get; set; }
        public decimal spurchase_amount { get; set; }
        public string s_type { get; set; }
        public int bill_no { get; set; }
        public string gstype { get; set; }
        public Nullable<decimal> discount_amount { get; set; }
        public string approved_by { get; set; }
        public string is_ins { get; set; }
        public Nullable<int> sr_billno { get; set; }
        public string item_set { get; set; }
        public string remarks { get; set; }
        public string approve_flag { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public Nullable<decimal> ed_cess { get; set; }
        public Nullable<decimal> hed_cess { get; set; }
        public Nullable<decimal> ed_cess_percent { get; set; }
        public Nullable<decimal> hed_cess_percent { get; set; }
        public Nullable<decimal> excise_duty_percent { get; set; }
        public Nullable<decimal> excise_duty_amount { get; set; }
        public Nullable<decimal> hi_scheme_amount { get; set; }
        public Nullable<int> hi_scheme_no { get; set; }
        public Nullable<decimal> hi_bonus_amount { get; set; }
        public string salutation { get; set; }
        public string New_Bill_No { get; set; }
        public string isPAN { get; set; }
        public Nullable<decimal> round_off { get; set; }
        public Nullable<int> state_code { get; set; }
        public Nullable<int> pos { get; set; }
        public string Corparate_ID { get; set; }
        public string Corporate_Branch_ID { get; set; }
        public string Employee_Id { get; set; }
        public string Registered_MN { get; set; }
        public string profession_ID { get; set; }
        public string Empcorp_Email_ID { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string address3 { get; set; }
        public string city { get; set; }
        public string pin_code { get; set; }
        public string mobile_no { get; set; }
        public string state { get; set; }
        public string tin { get; set; }
        public string pan_no { get; set; }
        public string id_type { get; set; }
        public string id_details { get; set; }
        public string booking_type { get; set; }
        public string phone_no { get; set; }
        public string Email_ID { get; set; }
        public byte[] RowRevision { get; set; }
        public Nullable<decimal> TotalDiscountVoucherAmt { get; set; }
        public string offerType { get; set; }
        public string CRM_ID { get; set; }
    }
}
