//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KTTU_STOCK_TAKING
    {
        public string obj_id { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public string item_name { get; set; }
        public string counter_code { get; set; }
        public int units { get; set; }
        public decimal gwt { get; set; }
        public decimal nwt { get; set; }
        public string sal_code { get; set; }
        public string barcode_no { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public Nullable<decimal> D_cts { get; set; }
        public Nullable<int> batch_no { get; set; }
    }
}
