//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KTTU_PURCHASE_STONE_DETAILS
    {
        public string obj_id { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public int bill_no { get; set; }
        public int sno { get; set; }
        public int est_no { get; set; }
        public int item_sno { get; set; }
        public string type { get; set; }
        public string name { get; set; }
        public int qty { get; set; }
        public decimal carrat { get; set; }
        public decimal rate { get; set; }
        public decimal amount { get; set; }
        public int pur_dealer_bill_no { get; set; }
        public string gs_code { get; set; }
        public Nullable<int> pur_return_no { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public Nullable<int> Fin_Year { get; set; }
        public System.Guid UniqRowID { get; set; }
    }
}
