//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KTTU_ORDER_MASTER
    {
        public string obj_id { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public int order_no { get; set; }
        public int Cust_Id { get; set; }
        public string cust_name { get; set; }
        public string order_type { get; set; }
        public string remarks { get; set; }
        public System.DateTime order_date { get; set; }
        public string operator_code { get; set; }
        public string sal_code { get; set; }
        public System.DateTime delivery_date { get; set; }
        public string order_rate_type { get; set; }
        public string gs_code { get; set; }
        public decimal rate { get; set; }
        public Nullable<decimal> advance_ord_amount { get; set; }
        public decimal grand_total { get; set; }
        public string object_status { get; set; }
        public int bill_no { get; set; }
        public string cflag { get; set; }
        public string cancelled_by { get; set; }
        public string bill_counter { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string closed_branch { get; set; }
        public string closed_flag { get; set; }
        public string closed_by { get; set; }
        public Nullable<System.DateTime> closed_date { get; set; }
        public string karat { get; set; }
        public Nullable<decimal> order_day_rate { get; set; }
        public string New_Bill_No { get; set; }
        public Nullable<decimal> tax_percentage { get; set; }
        public Nullable<decimal> total_amount_before_tax { get; set; }
        public Nullable<decimal> total_tax_amount { get; set; }
        public Nullable<int> ShiftID { get; set; }
        public string isPAN { get; set; }
        public Nullable<int> old_order_no { get; set; }
        public System.Guid UniqRowID { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string address3 { get; set; }
        public string city { get; set; }
        public string pin_code { get; set; }
        public string mobile_no { get; set; }
        public string state { get; set; }
        public Nullable<int> state_code { get; set; }
        public string tin { get; set; }
        public string pan_no { get; set; }
        public Nullable<int> est_no { get; set; }
        public string id_type { get; set; }
        public string id_details { get; set; }
        public string booking_type { get; set; }
        public string salutation { get; set; }
        public string phone_no { get; set; }
        public string Email_ID { get; set; }
        public string manager_code { get; set; }
        public string is_lock { get; set; }
        public Nullable<decimal> additional_amount { get; set; }
        public string order_reference_no { get; set; }
        public Nullable<int> order_source { get; set; }
        public string shipping_address { get; set; }
        public Nullable<System.DateTime> cancelled_date { get; set; }
        public string order_advance_rate_type { get; set; }
        public Nullable<System.DateTime> rate_fixed_till { get; set; }
        public string customer_type { get; set; }
        public Nullable<int> central_ref_no { get; set; }
        public Nullable<decimal> adv_percent { get; set; }
        public string market_place_order_no { get; set; }
        public string CustomerOrderID { get; set; }
        public string ShipmentID { get; set; }
        public Nullable<int> store_location_id { get; set; }
        public string Rflag { get; set; }
        public string Return_By { get; set; }
        public Nullable<System.DateTime> Return_Date { get; set; }
        public string Ruser_commenets { get; set; }
        public string Rreciver_commenets { get; set; }
    }
}
