//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KTTU_SR_DETAILS
    {
        public string obj_id { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public int sales_bill_no { get; set; }
        public int sl_no { get; set; }
        public int est_no { get; set; }
        public string sal_code { get; set; }
        public string item_name { get; set; }
        public string counter_code { get; set; }
        public int quantity { get; set; }
        public decimal gwt { get; set; }
        public decimal swt { get; set; }
        public decimal nwt { get; set; }
        public Nullable<decimal> wast_percent { get; set; }
        public Nullable<decimal> making_charge_per_rs { get; set; }
        public decimal va_amount { get; set; }
        public decimal sr_amount { get; set; }
        public Nullable<decimal> stone_charges { get; set; }
        public Nullable<decimal> diamond_charges { get; set; }
        public decimal net_amount { get; set; }
        public Nullable<int> Addqty { get; set; }
        public Nullable<int> Deductqty { get; set; }
        public Nullable<decimal> AddWt { get; set; }
        public Nullable<decimal> DeductWt { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public Nullable<decimal> va_percent { get; set; }
        public string gs_code { get; set; }
        public Nullable<int> Fin_Year { get; set; }
        public string barcode_no { get; set; }
        public string supplier_code { get; set; }
        public Nullable<decimal> item_additional_discount { get; set; }
        public Nullable<decimal> item_total_after_discount { get; set; }
        public Nullable<decimal> tax_percentage { get; set; }
        public Nullable<decimal> tax_amount { get; set; }
        public string item_size { get; set; }
        public string img_id { get; set; }
        public string design_code { get; set; }
        public string design_name { get; set; }
        public string batch_id { get; set; }
        public string rf_id { get; set; }
        public Nullable<decimal> mc_per_piece { get; set; }
        public Nullable<decimal> offer_value { get; set; }
        public Nullable<decimal> item_final_amount { get; set; }
        public Nullable<int> mc_type { get; set; }
        public Nullable<decimal> round_off { get; set; }
        public Nullable<decimal> item_final_amount_after_roundoff { get; set; }
        public string original_sales_bill_no { get; set; }
        public string item_type { get; set; }
        public Nullable<decimal> cst_amount { get; set; }
        public Nullable<decimal> Dcts { get; set; }
        public string GSTGroupCode { get; set; }
        public Nullable<decimal> SGST_Percent { get; set; }
        public Nullable<decimal> SGST_Amount { get; set; }
        public Nullable<decimal> CGST_Percent { get; set; }
        public Nullable<decimal> CGST_Amount { get; set; }
        public Nullable<decimal> IGST_Percent { get; set; }
        public Nullable<decimal> IGST_Amount { get; set; }
        public string HSN { get; set; }
        public Nullable<decimal> Discount_Mc { get; set; }
        public Nullable<decimal> Mc_Discount_Amt { get; set; }
        public System.Guid UniqRowID { get; set; }
        public Nullable<decimal> CESSPercent { get; set; }
        public Nullable<decimal> CESSAmount { get; set; }
        public string isBarcoded { get; set; }
        public Nullable<decimal> DiscountVoucherAmt { get; set; }
        public Nullable<decimal> OfferRatePerGram { get; set; }
    }
}
