//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KTTU_CASHBACK_OFFER_DETAILS
    {
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public int cash_back_no { get; set; }
        public int sl_no { get; set; }
        public int bill_no { get; set; }
        public decimal invoice_amount { get; set; }
        public decimal eligible_cash_back_amount { get; set; }
        public decimal actual_cash_back_amount { get; set; }
        public string remarks { get; set; }
        public int voucher_no { get; set; }
        public Nullable<System.DateTime> cash_back_date { get; set; }
        public string cflag { get; set; }
    }
}
