//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KTTU_COUNTER_STOCK
    {
        public string obj_id { get; set; }
        public string gs_code { get; set; }
        public string item_name { get; set; }
        public string counter_code { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public System.DateTime date { get; set; }
        public int op_units { get; set; }
        public decimal op_gwt { get; set; }
        public decimal op_swt { get; set; }
        public Nullable<decimal> op_nwt { get; set; }
        public int barcoded_units { get; set; }
        public decimal barcoded_gwt { get; set; }
        public Nullable<decimal> barcoded_swt { get; set; }
        public Nullable<decimal> barcoded_nwt { get; set; }
        public int sales_units { get; set; }
        public Nullable<decimal> sales_gwt { get; set; }
        public Nullable<decimal> sales_swt { get; set; }
        public decimal sales_nwt { get; set; }
        public int receipt_units { get; set; }
        public Nullable<decimal> receipt_gwt { get; set; }
        public Nullable<decimal> receipt_swt { get; set; }
        public decimal receipt_nwt { get; set; }
        public int issues_units { get; set; }
        public Nullable<decimal> issues_gwt { get; set; }
        public Nullable<decimal> issues_swt { get; set; }
        public decimal issues_nwt { get; set; }
        public int closing_units { get; set; }
        public Nullable<decimal> closing_gwt { get; set; }
        public Nullable<decimal> closing_swt { get; set; }
        public decimal closing_nwt { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public Nullable<int> Version { get; set; }
        public System.Guid UniqRowID { get; set; }
    }
}
