//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KTTU_CONFIRMED_BARCODE_MASTER
    {
        public string obj_id { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public string barcode_no { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<decimal> gwt { get; set; }
        public Nullable<decimal> swt { get; set; }
        public Nullable<decimal> nwt { get; set; }
        public Nullable<decimal> carrat { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string obj_status { get; set; }
        public string batch_id { get; set; }
        public string BReceiptNo { get; set; }
    }
}
