//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KTTU_CREDIT_BILL_DETAILS
    {
        public string Obj_Id { get; set; }
        public int bill_no { get; set; }
        public int credit_bill_receiptNo { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public string garunteename { get; set; }
        public decimal bill_amount { get; set; }
        public decimal amount_paid { get; set; }
        public decimal balance_amount { get; set; }
        public string Ispaid { get; set; }
        public Nullable<System.DateTime> Paid_date { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public Nullable<int> Fin_Year { get; set; }
        public string New_Bill_No { get; set; }
        public Nullable<decimal> tax_percentage { get; set; }
        public Nullable<decimal> total_amount_before_tax { get; set; }
        public Nullable<decimal> tota_tax_amount { get; set; }
        public System.Guid UniqRowID { get; set; }
    }
}
