//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KTTU_ORDER_PRODUCTION_ISSUE_DETAILS
    {
        public string obj_id { get; set; }
        public int issue_no { get; set; }
        public int slno { get; set; }
        public int order_no { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public System.DateTime order_date { get; set; }
        public System.DateTime order_due_date { get; set; }
        public decimal order_gwt { get; set; }
        public int order_qty { get; set; }
        public System.DateTime branch_due_date { get; set; }
        public string cflag { get; set; }
        public string description { get; set; }
        public string gs_code { get; set; }
        public string img_id { get; set; }
        public System.DateTime issue_date { get; set; }
        public string issued_by { get; set; }
        public string item_name { get; set; }
        public string operator_code { get; set; }
        public string remarks { get; set; }
        public string karat { get; set; }
        public Nullable<decimal> rate { get; set; }
        public string order_type { get; set; }
        public string salesman { get; set; }
        public string counter { get; set; }
        public Nullable<decimal> advanceamount { get; set; }
        public string sampleitem { get; set; }
        public Nullable<decimal> order_swt { get; set; }
        public Nullable<decimal> orderDCarrat { get; set; }
        public Nullable<decimal> order_nwt { get; set; }
        public string item_size { get; set; }
        public Nullable<int> refNo { get; set; }
        public Nullable<int> order_slno { get; set; }
        public Nullable<System.Guid> UniqRowID { get; set; }
        public string item_type { get; set; }
        public Nullable<decimal> app_swt { get; set; }
        public Nullable<System.DateTime> cdate { get; set; }
        public string isReceiveatCPC { get; set; }
        public string issue_to { get; set; }
        public string mobile_no { get; set; }
        public string cust_name { get; set; }
    }
}
