//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KTTU_PURCHASE_EST_MASTER
    {
        public string obj_id { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public int est_no { get; set; }
        public int bill_no { get; set; }
        public string pur_item { get; set; }
        public int cust_id { get; set; }
        public string cust_name { get; set; }
        public System.DateTime p_date { get; set; }
        public decimal tax { get; set; }
        public Nullable<decimal> today_rate { get; set; }
        public string operator_code { get; set; }
        public decimal grand_total { get; set; }
        public string p_type { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public Nullable<int> scheme_duratation { get; set; }
        public Nullable<decimal> total_tax_amount { get; set; }
        public Nullable<decimal> total_purchase_amount { get; set; }
        public Nullable<int> invoice_type { get; set; }
        public string salutation { get; set; }
        public string cflag { get; set; }
        public Nullable<decimal> ratededuct { get; set; }
        public string isPAN { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string address3 { get; set; }
        public string city { get; set; }
        public string pin_code { get; set; }
        public string mobile_no { get; set; }
        public string state { get; set; }
        public Nullable<int> state_code { get; set; }
        public string tin { get; set; }
        public string pan_no { get; set; }
        public string id_type { get; set; }
        public string id_details { get; set; }
        public string booking_type { get; set; }
        public string phone_no { get; set; }
        public string Email_ID { get; set; }
        public Nullable<int> diamondRateCalculation_type { get; set; }
        public Nullable<decimal> additional_amount { get; set; }
        public string calculatedFor { get; set; }
    }
}
