//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KTTU_SR_MASTER
    {
        public string obj_id { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public int voture_bill_no { get; set; }
        public int sales_bill_no { get; set; }
        public int est_no { get; set; }
        public int cust_id { get; set; }
        public System.DateTime bill_date { get; set; }
        public Nullable<System.DateTime> sr_date { get; set; }
        public string gs_type { get; set; }
        public Nullable<decimal> tax_amt { get; set; }
        public decimal total_sramount { get; set; }
        public string operator_code { get; set; }
        public string sal_code { get; set; }
        public string bill_counter { get; set; }
        public string remarks { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string is_ins { get; set; }
        public Nullable<decimal> rate { get; set; }
        public string billed_branch { get; set; }
        public string cflag { get; set; }
        public Nullable<decimal> excise_duty_percent { get; set; }
        public Nullable<decimal> ed_cess_percent { get; set; }
        public Nullable<decimal> hed_cess_percent { get; set; }
        public Nullable<decimal> excise_duty_amount { get; set; }
        public Nullable<decimal> ed_cess_amount { get; set; }
        public Nullable<decimal> hed_cess_amount { get; set; }
        public Nullable<decimal> discount_amt { get; set; }
        public string is_adjusted { get; set; }
        public string cancelled_by { get; set; }
        public string cancelled_remarks { get; set; }
        public string New_Bill_No { get; set; }
        public Nullable<decimal> round_off { get; set; }
        public Nullable<int> ShiftID { get; set; }
        public Nullable<int> invoice_type_id { get; set; }
        public Nullable<decimal> total_cst_amount { get; set; }
        public Nullable<decimal> vp_amt { get; set; }
        public Nullable<decimal> payable_amt { get; set; }
        public System.Guid UniqRowID { get; set; }
        public string cust_name { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string address3 { get; set; }
        public string city { get; set; }
        public string pin_code { get; set; }
        public string mobile_no { get; set; }
        public string state { get; set; }
        public Nullable<int> state_code { get; set; }
        public string tin { get; set; }
        public string pan_no { get; set; }
        public Nullable<int> store_location_id { get; set; }
        public Nullable<int> location_id { get; set; }
        public string discount_Auth_code { get; set; }
        public Nullable<decimal> TotalDiscountVoucherAmt { get; set; }
        public Nullable<int> inv_source { get; set; }
        public string offerType { get; set; }
    }
}
