//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KTTU_SALES_STOCK_MASTER
    {
        public string obj_id { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public int transfer_no { get; set; }
        public System.DateTime transfer_date { get; set; }
        public string transfer_by { get; set; }
        public int sales_bill_no { get; set; }
        public Nullable<System.DateTime> due_date { get; set; }
        public string remarks { get; set; }
        public int cust_id { get; set; }
        public string cust_name { get; set; }
        public string cflag { get; set; }
        public string cancelled_by { get; set; }
        public string cancelled_remarks { get; set; }
        public string gs_type { get; set; }
    }
}
