//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KTTU_PAYMENT_DETAILS_OLD
    {
        public string obj_id { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public int series_no { get; set; }
        public int receipt_no { get; set; }
        public int sno { get; set; }
        public string trans_type { get; set; }
        public string pay_mode { get; set; }
        public string pay_details { get; set; }
        public Nullable<System.DateTime> pay_date { get; set; }
        public Nullable<decimal> pay_amt { get; set; }
        public string Ref_BillNo { get; set; }
        public string party_code { get; set; }
        public string bill_counter { get; set; }
        public string is_paid { get; set; }
        public string bank { get; set; }
        public string bank_name { get; set; }
        public Nullable<System.DateTime> cheque_date { get; set; }
        public string card_type { get; set; }
        public Nullable<System.DateTime> expiry_date { get; set; }
        public string cflag { get; set; }
        public string card_app_no { get; set; }
        public string scheme_code { get; set; }
        public string sal_bill_type { get; set; }
        public string operator_code { get; set; }
        public Nullable<int> session_no { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string cheque_no { get; set; }
        public string group_code { get; set; }
        public Nullable<decimal> amt_received { get; set; }
        public Nullable<decimal> bonus_amt { get; set; }
        public Nullable<decimal> win_amt { get; set; }
        public string ct_branch { get; set; }
        public Nullable<int> fin_year { get; set; }
        public Nullable<decimal> CardCharges { get; set; }
        public string New_Bill_No { get; set; }
        public Nullable<decimal> Add_disc { get; set; }
    }
}
