//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KTTU_SR_ISSUE_STONE_DETAILS
    {
        public string obj_id { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public int issue_no { get; set; }
        public int sales_bill_no { get; set; }
        public int item_slno { get; set; }
        public int sl_no { get; set; }
        public string gs_code { get; set; }
        public string item_name { get; set; }
        public int qty { get; set; }
        public decimal carrat { get; set; }
        public decimal rate { get; set; }
        public decimal amount { get; set; }
        public Nullable<int> Fin_Year { get; set; }
        public string barcode_no { get; set; }
        public System.Guid UniqRowID { get; set; }
    }
}
