//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KTTU_PURCHASE_RETURN_DETAILS
    {
        public string obj_id { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public int pur_return_no { get; set; }
        public int s_no { get; set; }
        public string bill_type { get; set; }
        public string inv_ref_no { get; set; }
        public string item_name { get; set; }
        public Nullable<int> units { get; set; }
        public Nullable<decimal> gwt { get; set; }
        public Nullable<decimal> swt { get; set; }
        public Nullable<decimal> nwt { get; set; }
        public decimal item_amount { get; set; }
        public decimal pur_return_rate { get; set; }
        public string pur_item { get; set; }
        public decimal vat { get; set; }
        public Nullable<decimal> purity { get; set; }
        public Nullable<decimal> std_qty { get; set; }
        public Nullable<decimal> wastage { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string gs_code { get; set; }
        public Nullable<decimal> Stone_Charges { get; set; }
        public Nullable<decimal> va_amount { get; set; }
        public Nullable<decimal> metal_amount { get; set; }
        public Nullable<int> Fin_Year { get; set; }
        public Nullable<decimal> Dcts { get; set; }
        public Nullable<decimal> cst { get; set; }
        public Nullable<decimal> dcts_amount { get; set; }
        public Nullable<decimal> std_weight { get; set; }
        public string barcode_no { get; set; }
        public Nullable<int> version { get; set; }
        public string GSTGroupCode { get; set; }
        public Nullable<decimal> SGST_Percent { get; set; }
        public Nullable<decimal> SGST_Amount { get; set; }
        public Nullable<decimal> CGST_Percent { get; set; }
        public Nullable<decimal> CGST_Amount { get; set; }
        public Nullable<decimal> IGST_Percent { get; set; }
        public Nullable<decimal> IGST_Amount { get; set; }
        public string HSN { get; set; }
        public System.Guid UniqRowID { get; set; }
        public string batch_id { get; set; }
        public string counter_code { get; set; }
        public string design_code { get; set; }
        public Nullable<int> mc_type { get; set; }
        public Nullable<decimal> mc_per_gram { get; set; }
        public Nullable<decimal> piece_rate { get; set; }
        public Nullable<decimal> other_amount { get; set; }
    }
}
