//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KTTU_STONE_COUNTER_STOCK
    {
        public string obj_id { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public string counter_code { get; set; }
        public string stone_name { get; set; }
        public string gs_code { get; set; }
        public int op_qty { get; set; }
        public decimal op_carat { get; set; }
        public int barcoded_qty { get; set; }
        public decimal barcoded_carat { get; set; }
        public int sal_qty { get; set; }
        public decimal sal_carat { get; set; }
        public int issued_qty { get; set; }
        public decimal issued_carat { get; set; }
        public int receipt_qty { get; set; }
        public decimal receipt_carat { get; set; }
        public int closing_qty { get; set; }
        public decimal closing_carat { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string batch_no { get; set; }
        public Nullable<int> version { get; set; }
        public Nullable<System.DateTime> counter_date { get; set; }
        public System.Guid UniqRowID { get; set; }
    }
}
