//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KTTU_CASHBACK_OFFER_MASTER
    {
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public int cash_back_no { get; set; }
        public System.DateTime cash_back_date { get; set; }
        public string operator_code { get; set; }
        public decimal total_invoice_amount { get; set; }
        public decimal total_cash_back_amount { get; set; }
        public int voucher_no { get; set; }
        public string cflag { get; set; }
    }
}
