//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KTTU_ORDER_RECEIPT_DETAILS
    {
        public string obj_id { get; set; }
        public string company_code { get; set; }
        public string bracnch_code { get; set; }
        public int order_receipt_no { get; set; }
        public int cust_id { get; set; }
        public System.DateTime receipt_date { get; set; }
        public decimal receipt_amount { get; set; }
        public string object_status { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public Nullable<int> Fin_Year { get; set; }
        public Nullable<decimal> tax_percentage { get; set; }
        public Nullable<decimal> receipt_amount_before_tax { get; set; }
        public Nullable<decimal> tax_amount { get; set; }
        public Nullable<int> order_no { get; set; }
        public string New_Bill_No { get; set; }
        public Nullable<decimal> OnDayRate { get; set; }
    }
}
