//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KTTU_ISSUE_DETAILS
    {
        public string obj_id { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public int issue_no { get; set; }
        public int sl_no { get; set; }
        public string item_name { get; set; }
        public string code { get; set; }
        public int units { get; set; }
        public Nullable<decimal> gwt { get; set; }
        public Nullable<decimal> swt { get; set; }
        public Nullable<decimal> nwt { get; set; }
        public Nullable<decimal> alloy { get; set; }
        public string receipt_gs_desc { get; set; }
        public Nullable<decimal> purity { get; set; }
        public Nullable<decimal> std_weight { get; set; }
        public Nullable<decimal> wastage { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public Nullable<int> oldIssueNo { get; set; }
        public string gs_code { get; set; }
        public string batch_id { get; set; }
        public Nullable<int> opg_receipt_no { get; set; }
        public string counter_code { get; set; }
        public Nullable<int> no_tags { get; set; }
        public Nullable<decimal> tag_wt { get; set; }
        public Nullable<decimal> dcts { get; set; }
        public string design_code { get; set; }
        public string batch_name { get; set; }
        public string barcode_no { get; set; }
        public Nullable<int> ref_no { get; set; }
        public Nullable<decimal> item_value { get; set; }
        public Nullable<int> Fin_Year { get; set; }
        public Nullable<int> receipt_no { get; set; }
        public Nullable<decimal> total_wt { get; set; }
        public decimal wastageInActualWeight { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<int> Version { get; set; }
        public Nullable<decimal> mc_amount { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string mc_for { get; set; }
        public string GSTGroupCode { get; set; }
        public Nullable<decimal> SGST_Percent { get; set; }
        public Nullable<decimal> SGST_Amount { get; set; }
        public Nullable<decimal> CGST_Percent { get; set; }
        public Nullable<decimal> CGST_Amount { get; set; }
        public Nullable<decimal> IGST_Percent { get; set; }
        public Nullable<decimal> IGST_Amount { get; set; }
        public string HSN { get; set; }
        public string IsScrap { get; set; }
        public System.Guid UniqRowID { get; set; }
        public Nullable<int> TID { get; set; }
        public string U_obj_id { get; set; }
        public string isReceived { get; set; }
        public Nullable<decimal> kova_wt { get; set; }
        public string stn_gs_code { get; set; }
        public string dm_gs_code { get; set; }
    }
}
