//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KTTU_PITTY_CASH_ENTRY
    {
        public string obj_id { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public int voucher_no { get; set; }
        public System.DateTime voucher_date { get; set; }
        public string cash_head { get; set; }
        public decimal amount { get; set; }
        public string narration { get; set; }
        public string cash_type { get; set; }
        public string obj_status { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
    }
}
