//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KTTU_COUNTER_TRANSFER_LOG
    {
        public string obj_id { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public int transfer_no { get; set; }
        public string barcode_no { get; set; }
        public System.DateTime transfer_date { get; set; }
        public string operator_code { get; set; }
        public string from_counter { get; set; }
        public string to_counter { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string transfer_type { get; set; }
    }
}
