//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KTTU_RECEIPTS_DETAILS
    {
        public string obj_id { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public int receipt_no { get; set; }
        public int sl_no { get; set; }
        public string item_name { get; set; }
        public string code { get; set; }
        public string counter_code { get; set; }
        public int item_no { get; set; }
        public Nullable<decimal> gwt { get; set; }
        public Nullable<decimal> swt { get; set; }
        public Nullable<decimal> nwt { get; set; }
        public decimal wastage { get; set; }
        public Nullable<decimal> item_amount { get; set; }
        public Nullable<decimal> std_weight { get; set; }
        public Nullable<decimal> purity { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public Nullable<int> oldReceiptNo { get; set; }
        public string gs_code { get; set; }
        public string batch_id { get; set; }
        public Nullable<int> no_tags { get; set; }
        public Nullable<decimal> tag_wt { get; set; }
        public Nullable<decimal> dcts { get; set; }
        public string design_code { get; set; }
        public string result { get; set; }
        public Nullable<decimal> KOVA_wt { get; set; }
        public string batch_name { get; set; }
        public Nullable<decimal> supp_dcts { get; set; }
        public Nullable<decimal> hLoss { get; set; }
        public Nullable<decimal> supp_swt { get; set; }
        public Nullable<int> Fin_Year { get; set; }
        public string barcode_no { get; set; }
        public Nullable<decimal> dcts_amount { get; set; }
        public Nullable<int> sales_no { get; set; }
        public Nullable<System.DateTime> adj_date { get; set; }
        public Nullable<int> mc_type { get; set; }
        public Nullable<decimal> mc_per_gram { get; set; }
        public Nullable<decimal> mc_amount { get; set; }
        public Nullable<decimal> tax_amount { get; set; }
        public string item_description { get; set; }
        public Nullable<decimal> stone_amount { get; set; }
        public Nullable<decimal> piece_rate { get; set; }
        public string type { get; set; }
        public string isHallMarked { get; set; }
        public int wastage_type_id { get; set; }
        public Nullable<decimal> wastage_type_value { get; set; }
        public Nullable<decimal> wastageInActualWeight { get; set; }
        public string isScrap { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> Hallmark_charges { get; set; }
        public Nullable<decimal> certification_charges { get; set; }
        public Nullable<decimal> other_charges { get; set; }
        public Nullable<int> version { get; set; }
        public string mc_for { get; set; }
        public string GSTGroupCode { get; set; }
        public Nullable<decimal> SGST_Percent { get; set; }
        public Nullable<decimal> SGST_Amount { get; set; }
        public Nullable<decimal> CGST_Percent { get; set; }
        public Nullable<decimal> CGST_Amount { get; set; }
        public Nullable<decimal> IGST_Percent { get; set; }
        public Nullable<decimal> IGST_Amount { get; set; }
        public string HSN { get; set; }
        public int TID { get; set; }
        public System.Guid UniqRowID { get; set; }
        public Nullable<decimal> wastagedcts { get; set; }
        public string isReceived { get; set; }
        public string isDiamondCalculationFlag { get; set; }
        public Nullable<decimal> mc_percent { get; set; }
        public Nullable<decimal> mc_per_piece { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<decimal> AddWt { get; set; }
        public Nullable<decimal> DeductWt { get; set; }
        public string stn_gs_code { get; set; }
        public string dm_gs_code { get; set; }
    }
}
