//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KTTU_SALES_STONE_DETAILS
    {
        public string obj_id { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public int bill_no { get; set; }
        public int sl_no { get; set; }
        public int est_no { get; set; }
        public int est_Srno { get; set; }
        public string barcode_no { get; set; }
        public string type { get; set; }
        public string name { get; set; }
        public int qty { get; set; }
        public decimal carrat { get; set; }
        public Nullable<decimal> stone_wt { get; set; }
        public Nullable<decimal> rate { get; set; }
        public decimal amount { get; set; }
        public decimal tax { get; set; }
        public decimal tax_amount { get; set; }
        public decimal total_amount { get; set; }
        public string bill_type { get; set; }
        public Nullable<int> dealer_sales_no { get; set; }
        public Nullable<int> BILL_DET11PK { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public Nullable<int> Fin_Year { get; set; }
        public string color { get; set; }
        public string clarity { get; set; }
        public string shape { get; set; }
        public string cut { get; set; }
        public string polish { get; set; }
        public string symmetry { get; set; }
        public string fluorescence { get; set; }
        public string certificate { get; set; }
        public System.Guid UniqRowID { get; set; }
        public int SalesStoneDetailID { get; set; }
    }
}
