//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KTTU_ORDER_DETAILS
    {
        public string obj_id { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public int order_no { get; set; }
        public int slno { get; set; }
        public string item_name { get; set; }
        public int quantity { get; set; }
        public string description { get; set; }
        public decimal from_gwt { get; set; }
        public decimal to_gwt { get; set; }
        public decimal mc_per { get; set; }
        public decimal wst_per { get; set; }
        public decimal amt { get; set; }
        public string s_flag { get; set; }
        public string s_party { get; set; }
        public int bill_no { get; set; }
        public string img_id { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public decimal va_percent { get; set; }
        public decimal item_amt { get; set; }
        public string gs_code { get; set; }
        public Nullable<int> Fin_Year { get; set; }
        public Nullable<decimal> itemwise_tax_percentage { get; set; }
        public Nullable<decimal> itemwise_tax_amount { get; set; }
        public Nullable<decimal> mcperpiece { get; set; }
        public string productid { get; set; }
        public string is_Issued { get; set; }
        public string counter_code { get; set; }
        public string sal_code { get; set; }
        public Nullable<decimal> mc_percent { get; set; }
        public Nullable<int> mc_type { get; set; }
        public System.Guid UniqRowID { get; set; }
        public Nullable<int> est_no { get; set; }
        public string item_type { get; set; }
        public Nullable<decimal> app_swt { get; set; }
        public string barcode_no { get; set; }
        public Nullable<System.DateTime> due_date_for_shipment { get; set; }
        public Nullable<bool> isProcessed { get; set; }
        public Nullable<System.DateTime> processed_date { get; set; }
        public Nullable<bool> isPicked { get; set; }
        public Nullable<System.DateTime> picked_date { get; set; }
        public Nullable<bool> isPacked { get; set; }
        public Nullable<System.DateTime> packed_date { get; set; }
        public Nullable<bool> isScheduledForPickUp { get; set; }
        public Nullable<System.DateTime> scheduled_for_pickup_date { get; set; }
        public Nullable<bool> isShipped { get; set; }
        public Nullable<System.DateTime> shipped_date { get; set; }
        public Nullable<int> MarketPlaceSNo { get; set; }
        public Nullable<bool> isGiftWrapRequested { get; set; }
        public Nullable<bool> isGiftMessageAdded { get; set; }
        public string GiftMessage { get; set; }
        public string Item_Size { get; set; }
        public Nullable<decimal> rate_per_gram { get; set; }
        public Nullable<decimal> va_amount { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public Nullable<decimal> DiamondAmount { get; set; }
        public Nullable<decimal> StoneAmount { get; set; }
        public Nullable<decimal> ShippingCharges { get; set; }
    }
}
