//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KTTU_BARCODE_MASTER
    {
        public string obj_id { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public string barcode_no { get; set; }
        public Nullable<int> batch_no { get; set; }
        public string sal_code { get; set; }
        public string operator_code { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string counter_code { get; set; }
        public string gs_code { get; set; }
        public string item_name { get; set; }
        public Nullable<decimal> gwt { get; set; }
        public Nullable<decimal> swt { get; set; }
        public Nullable<decimal> nwt { get; set; }
        public string grade { get; set; }
        public string catalog_id { get; set; }
        public Nullable<decimal> making_charge_per_rs { get; set; }
        public Nullable<decimal> wast_percent { get; set; }
        public Nullable<int> qty { get; set; }
        public string item_size { get; set; }
        public string design_no { get; set; }
        public Nullable<decimal> piece_rate { get; set; }
        public Nullable<decimal> daimond_amount { get; set; }
        public Nullable<decimal> stone_amount { get; set; }
        public Nullable<int> order_no { get; set; }
        public string sold_flag { get; set; }
        public string product_code { get; set; }
        public Nullable<decimal> hallmark_charges { get; set; }
        public string remarks { get; set; }
        public string supplier_code { get; set; }
        public string ordered_company_code { get; set; }
        public string ordered_branch_code { get; set; }
        public string karat { get; set; }
        public Nullable<decimal> mc_amount { get; set; }
        public Nullable<decimal> wastage_grms { get; set; }
        public Nullable<decimal> mc_percent { get; set; }
        public string mc_type { get; set; }
        public string old_barcode_no { get; set; }
        public string prod_ida { get; set; }
        public string prod_tagno { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public Nullable<int> Lot_No { get; set; }
        public Nullable<decimal> tag_wt { get; set; }
        public string isConfirmed { get; set; }
        public string confirmedBy { get; set; }
        public Nullable<System.DateTime> confirmedDate { get; set; }
        public Nullable<decimal> current_wt { get; set; }
        public string MC_For { get; set; }
        public Nullable<int> diamond_no { get; set; }
        public string batch_id { get; set; }
        public Nullable<decimal> add_wt { get; set; }
        public string weightRead { get; set; }
        public string confirmedweightRead { get; set; }
        public string party_name { get; set; }
        public string design_name { get; set; }
        public string item_size_name { get; set; }
        public string master_design_code { get; set; }
        public string master_design_name { get; set; }
        public string vendor_model_no { get; set; }
        public Nullable<decimal> pur_mc_gram { get; set; }
        public Nullable<decimal> mc_per_piece { get; set; }
        public string Tagging_Type { get; set; }
        public string BReceiptNo { get; set; }
        public Nullable<int> BSNo { get; set; }
        public string Issue_To { get; set; }
        public Nullable<decimal> pur_mc_amount { get; set; }
        public Nullable<int> pur_mc_type { get; set; }
        public Nullable<decimal> pur_rate { get; set; }
        public string sr_batch_id { get; set; }
        public Nullable<decimal> total_selling_mc { get; set; }
        public Nullable<decimal> pur_diamond_amount { get; set; }
        public Nullable<decimal> total_purchase_mc { get; set; }
        public Nullable<decimal> pur_stone_amount { get; set; }
        public decimal pur_purity_percentage { get; set; }
        public int pur_wastage_type { get; set; }
        public decimal pur_wastage_type_value { get; set; }
        public System.Guid UniqRowID { get; set; }
        public string certification_no { get; set; }
        public string ref_no { get; set; }
        public string receipt_type { get; set; }
        public string EntryDocType { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string EntryDocNo { get; set; }
        public string ExitDocType { get; set; }
        public Nullable<System.DateTime> ExitDate { get; set; }
        public string ExitDocNo { get; set; }
        public string OnlineStock { get; set; }
        public string is_shuffled { get; set; }
        public Nullable<System.DateTime> shuffled_date { get; set; }
        public string Collections { get; set; }
        public string isActive { get; set; }
        public string product_description { get; set; }
        public string HUIDCode { get; set; }
        public Nullable<int> isDepartmentStock { get; set; }
        public string isDamaged { get; set; }
    }
}
