//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KTTU_ORDER_IMAGE
    {
        public string obj_id { get; set; }
        public int Order_no { get; set; }
        public int Slno { get; set; }
        public string Company_code { get; set; }
        public string Branch_code { get; set; }
        public byte[] ImageValues { get; set; }
    }
}
