//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KTTU_OPG_STOCK_ISSUE_MASTER
    {
        public string obj_id { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public int issue_no { get; set; }
        public string issued_to { get; set; }
        public string issued_by { get; set; }
        public System.DateTime issued_date { get; set; }
        public string operator_code { get; set; }
        public string gs_code { get; set; }
        public Nullable<int> total_qty { get; set; }
        public Nullable<decimal> total_gwt { get; set; }
        public Nullable<decimal> total_swt { get; set; }
        public Nullable<decimal> total_nwt { get; set; }
        public Nullable<decimal> total_amount { get; set; }
        public string cflag { get; set; }
        public string cancelled_by { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string cancelled_remarks { get; set; }
        public int New_Bill_No { get; set; }
        public Nullable<int> ShiftID { get; set; }
        public Nullable<decimal> SGST_Percent { get; set; }
        public Nullable<decimal> SGST_Amount { get; set; }
        public Nullable<decimal> CGST_Percent { get; set; }
        public Nullable<decimal> CGST_Amount { get; set; }
        public Nullable<decimal> IGST_Percent { get; set; }
        public Nullable<decimal> IGST_Amount { get; set; }
        public string issue_type { get; set; }
        public System.Guid UniqRowID { get; set; }
        public Nullable<int> store_location_id { get; set; }
    }
}
