//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KTTU_SR_RECEIPT_MASTER
    {
        public string obj_id { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public int receipt_no { get; set; }
        public int issue_no { get; set; }
        public string receipt_from { get; set; }
        public string received_by { get; set; }
        public System.DateTime receipt_date { get; set; }
        public string operator_code { get; set; }
        public string gs_code { get; set; }
        public string cflag { get; set; }
        public string cancelled_by { get; set; }
        public System.DateTime UpdateOn { get; set; }
        public string cancelled_remarks { get; set; }
        public System.Guid UniqRowID { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<decimal> CGST_Amount { get; set; }
        public Nullable<decimal> CGST_Percent { get; set; }
        public Nullable<decimal> final_amount { get; set; }
        public string GSTGroupCode { get; set; }
        public Nullable<decimal> IGST_Amount { get; set; }
        public Nullable<decimal> IGST_Percent { get; set; }
        public Nullable<decimal> SGST_Amount { get; set; }
        public Nullable<decimal> SGST_Percent { get; set; }
    }
}
