//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class KTTU_ONLINE_INVENTARY_DETAILS
    {
        public int ID { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public string barcode_no { get; set; }
        public int portal_id { get; set; }
        public string isActive { get; set; }
        public string gs_code { get; set; }
        public string item_name { get; set; }
        public Nullable<int> qty { get; set; }
        public Nullable<decimal> gwt { get; set; }
        public Nullable<decimal> nwt { get; set; }
    }
}
