//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class LastUpdateTime
    {
        public string Branch { get; set; }
        public Nullable<System.DateTime> LastUpdateTime1 { get; set; }
        public int Slno { get; set; }
        public string ConnectionString { get; set; }
    }
}
