//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class LedgerBalance
    {
        public int acc_code { get; set; }
        public string AName { get; set; }
        public string group { get; set; }
        public decimal OBalance { get; set; }
        public decimal DR { get; set; }
        public decimal CR { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public string SubGroupName { get; set; }
    }
}
