//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOV
    {
        public int LOVID { get; set; }
        public int LOVKeyID { get; set; }
        public string Name { get; set; }
        public Nullable<short> Sequence { get; set; }
    
        public virtual LOVKey LOVKey { get; set; }
    }
}
