//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class MobileOTP
    {
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public string computer_name { get; set; }
        public string operator_code { get; set; }
        public string OTPtype { get; set; }
        public int OTP { get; set; }
        public System.DateTime ValidTill { get; set; }
        public string IsUsed { get; set; }
        public int docno { get; set; }
        public string isexpired { get; set; }
        public Nullable<System.DateTime> UsedTime { get; set; }
        public Nullable<int> smsID { get; set; }
        public string authenticated_by { get; set; }
    }
}
