//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleFunction
    {
        public string CompanyCode { get; set; }
        public string BranchCode { get; set; }
        public int RoleID { get; set; }
        public int SubModuleID { get; set; }
        public string SubModuleName { get; set; }
        public int FunctionID { get; set; }
        public string FunctionName { get; set; }
        public string DefaultKey { get; set; }
    }
}
