//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItemPickList
    {
        public string obj_id { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public int assignment_no { get; set; }
        public int order_no { get; set; }
        public int order_item_sl_no { get; set; }
        public string gs_code { get; set; }
        public string item_name { get; set; }
        public string counter_code { get; set; }
        public string barcode_no { get; set; }
        public decimal gwt { get; set; }
        public bool isPicked { get; set; }
        public System.DateTime picked_date { get; set; }
        public string picked_by { get; set; }
        public string sku { get; set; }
    }
}
