//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItemShipmentLabel
    {
        public int Id { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public string order_ref_no { get; set; }
        public int order_no { get; set; }
        public int bill_no { get; set; }
        public string shipLabel { get; set; }
        public System.DateTime shipLabelCreatedDate { get; set; }
        public string operator_code { get; set; }
        public string ShipLabelPDFObject { get; set; }
        public string isScheduledforPickUp { get; set; }
        public string PickUpTokenNo { get; set; }
    }
}
