//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER_TYPE_ACC_POSTING
    {
        public string obj_id { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public string booking_code { get; set; }
        public string booking_name { get; set; }
        public int acc_code { get; set; }
        public string operator_code { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string obj_status { get; set; }
        public string order_rate_type { get; set; }
    }
}
