//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackageHeader
    {
        public int ID { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public string PackageCode { get; set; }
        public int OrderID { get; set; }
        public string MarketPlaceOrderID { get; set; }
        public decimal Length { get; set; }
        public decimal Width { get; set; }
        public decimal Height { get; set; }
        public decimal Weight { get; set; }
        public string LengthDimensionUnit { get; set; }
        public string WidthDimensionUnit { get; set; }
        public string HeightDimensionUnit { get; set; }
        public string WeightDimensionUnit { get; set; }
        public System.DateTime DoP { get; set; }
        public string PackageID { get; set; }
        public string OrderLineItemNo { get; set; }
        public int qty { get; set; }
        public string OTLNos { get; set; }
        public Nullable<int> PackageCreatedStatus { get; set; }
    }
}
