//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentJournal
    {
        public int ID { get; set; }
        public string CompanyCode { get; set; }
        public string BranchCode { get; set; }
        public string TransType { get; set; }
        public int SeriesNo { get; set; }
        public string PayMode { get; set; }
        public string Detail { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string RefBillNo { get; set; }
        public string PartyCode { get; set; }
        public string Bank { get; set; }
        public string BankName { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public string CardType { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string CardApprovalNo { get; set; }
        public string SchemeBranch { get; set; }
        public string SchemeCode { get; set; }
        public string GroupCode { get; set; }
        public Nullable<int> SchemeMSNo { get; set; }
        public string OperatorCode { get; set; }
        public Nullable<decimal> AmountReceived { get; set; }
        public Nullable<decimal> BonusAmt { get; set; }
        public Nullable<decimal> WonAmt { get; set; }
        public Nullable<decimal> GiftAmount { get; set; }
        public Nullable<decimal> CardCharges { get; set; }
        public string ChequeNo { get; set; }
        public Nullable<decimal> AddOnDicount { get; set; }
        public string CardSwipedBy { get; set; }
        public System.DateTime UpdateOn { get; set; }
    }
}
