//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefreshToken
    {
        public int ID { get; set; }
        public string Token { get; set; }
        public int ClientID { get; set; }
        public string UserCode { get; set; }
        public Nullable<System.DateTime> IssuedDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string ProtectedTicket { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
    
        public virtual APIClient APIClient { get; set; }
    }
}
