//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolePermission
    {
        public int RoleID { get; set; }
        public string CompanyCode { get; set; }
        public string BranchCode { get; set; }
        public int ModuleID { get; set; }
        public string ModuleName { get; set; }
        public string SubModuleID { get; set; }
        public Nullable<int> ModuleSeqNo { get; set; }
        public string SubModuleName { get; set; }
        public int SubModuleSeqNo { get; set; }
        public string AngularUIRoute { get; set; }
        public string Icon { get; set; }
        public string Class { get; set; }
        public string Label { get; set; }
        public string LabelClass { get; set; }
        public string MasterAngularUIRoute { get; set; }
        public string MasterIcon { get; set; }
        public string MasterClass { get; set; }
        public string MasterLabel { get; set; }
        public string MasterLabelClass { get; set; }
        public string FormType { get; set; }
        public string ReportServerType { get; set; }
        public string ReportApiRoute { get; set; }
    }
}
