//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class SDTS_SUBMODULE_MASTER
    {
        public string obj_id { get; set; }
        public string SubModuleName { get; set; }
        public int ModuleID { get; set; }
        public int ModuleSqNo { get; set; }
        public string IsAutoApp { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public string flag { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
        public string obj_status { get; set; }
        public string AngularUIRoute { get; set; }
        public string Icon { get; set; }
        public string Class { get; set; }
        public string Label { get; set; }
        public string LabelClass { get; set; }
        public string FormType { get; set; }
        public string ReportServerType { get; set; }
        public string ReportApiRoute { get; set; }
    }
}
