//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipmentMaster
    {
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public int shipment_no { get; set; }
        public string operator_code { get; set; }
        public System.DateTime shiped_date { get; set; }
        public string logistics_code { get; set; }
        public string logistic_person_name { get; set; }
        public string logistic_person_mobile { get; set; }
        public string remarks { get; set; }
        public string cflag { get; set; }
        public System.DateTime cancelled_date { get; set; }
        public string MarketPlaceCode { get; set; }
    }
}
