//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipmentDetail
    {
        public int Id { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public int shipment_no { get; set; }
        public int order_no { get; set; }
        public int item_sl_no { get; set; }
        public string barcode_no { get; set; }
        public string shipment_id { get; set; }
        public string package_id { get; set; }
    }
}
