//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSLog
    {
        public int ID { get; set; }
        public string SMSText { get; set; }
        public string MobileNo { get; set; }
        public Nullable<System.DateTime> InsertedOn { get; set; }
        public string GatewayStatus { get; set; }
        public Nullable<bool> IsMessageSent { get; set; }
        public Nullable<System.DateTime> DeliveredOn { get; set; }
    }
}
