//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDTU_SETTING_MASTER
    {
        public string obj_id { get; set; }
        public string OperartorCode { get; set; }
        public string FormName { get; set; }
        public Nullable<int> FormWidth { get; set; }
        public Nullable<int> FormtHeight { get; set; }
        public string tbbackcolor { get; set; }
        public string tbFontname { get; set; }
        public string tbfontstyle { get; set; }
        public Nullable<decimal> tbFontSize { get; set; }
        public string tbTxtcolcor { get; set; }
        public string tbTxtFontname { get; set; }
        public string tbTxtFontStyle { get; set; }
        public Nullable<decimal> tbTxtFontsize { get; set; }
        public string btncolor { get; set; }
        public string btnFontName { get; set; }
        public string btnFontStyle { get; set; }
        public Nullable<decimal> btnFontSize { get; set; }
        public string lblColor { get; set; }
        public string lblFontName { get; set; }
        public string lblFontStyle { get; set; }
        public Nullable<decimal> lblFontSize { get; set; }
        public string tbxColor { get; set; }
        public string tbxFontName { get; set; }
        public string tbxFontStyle { get; set; }
        public Nullable<decimal> tbxFontSize { get; set; }
        public string meBackcolor { get; set; }
        public string meFontname { get; set; }
        public string mefontstyle { get; set; }
        public Nullable<decimal> meFontSize { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
    }
}
