//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class vConversionBatchId
    {
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public string gs_code { get; set; }
        public Nullable<decimal> gwt { get; set; }
        public Nullable<decimal> swt { get; set; }
        public Nullable<decimal> nwt { get; set; }
        public string received_from { get; set; }
        public string BatchId { get; set; }
    }
}
