//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class vGetexpenseledger
    {
        public int acc_code { get; set; }
        public string acc_name { get; set; }
        public string company_code { get; set; }
        public string branch_code { get; set; }
        public string obj_status { get; set; }
        public string ledger_type { get; set; }
        public string party_code { get; set; }
        public Nullable<int> tds_id { get; set; }
        public string tin { get; set; }
        public string v_type { get; set; }
        public string pan { get; set; }
    }
}
