//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdigyAPI.Model.MagnaDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebAPITraceLog
    {
        public int ID { get; set; }
        public System.DateTime LoggedOn { get; set; }
        public string UserName { get; set; }
        public string IPAddress { get; set; }
        public string RequestMethod { get; set; }
        public string RequestURI { get; set; }
        public string ContentType { get; set; }
        public string UserAgent { get; set; }
        public string RequestBody { get; set; }
        public string HeaderAuthorization { get; set; }
        public Nullable<System.DateTime> RequestTimestamp { get; set; }
        public string ResponsePhrase { get; set; }
        public Nullable<bool> IsSuccessStatusCode { get; set; }
        public string ReponseBody { get; set; }
        public Nullable<System.DateTime> ResponseTimestamp { get; set; }
    }
}
