export interface ReceiptModel {
    PayMode: string,
    RefBillNo: number,
    CardNo: number,
    CardAppNo: number,
    CardType: string,
    BankName: string,
    Bank: string,
    ExpiryDate: string,
    CardCharges: number,
    CardSwipedBy: string,
    ChequeNo: number,
    ChequeDate: number,
    Details: string,
    AmtReceived: number,
    SchemeCode: string,
    GroupCode: string,
    CTBranch: string,
    PayAmount: string
}

export interface OrderHeader {
    CustID: number,
    OrderType: string,
    Remarks: string,
    OrderDate: string,
    OperatorCode: string,
    SalCode: string,
    DeliveryDate: string,
    OrderRateType: string,
    gsCode: string,
    Rate: number,
    AdvacnceOrderAmount: number,
    GrandTotal: number,
    ObjectStatus: string,
    BillNo: number,
    CFlag: string,
    CancelledBy: string,
    BillCounter: string,
    Karat: string,
    lstOfOrderItemDetailsVM: [],
    lstOfPaymentVM: []
}

// export interface ItemDetailsLines{
//      OrderNo:number,
//      SlNo:number,
//      ItemName:string,
//      Quantity:number,
//      Description:string,
//      FromGrossWt:number,
//      ToGrossWt:number,
//      MCPer:number,
//      WastagePercent:number,
//      Amount:number,
//      ImgID:string,
//      VAPercent:number,
//      ItemAmount:number,
//      GSCode:string,
//      FinYear:number,
//      ItemwiseTaxPercentage:number,
//      ItemwiseTaxAmount:number,
//      MCPerPiece:number,
//      ProductID:string,
//      IsIssued:string,
//      CounterCode:string,
//      SalCode:string,
//      MCPercent:number,
//      MCType:number,
// }


export interface ItemDetailsLines {
    ObjID: string,
    CompanyCode: string,
    BranchCode: string,
    OrderNo: number,
    SlNo: number,
    ItemName: string,
    Quantity: number,
    Description: string,
    FromGrossWt: number,
    ToGrossWt: number,
    ItemType: string,
    AppSwt: number,
    MCPer: number,
    ManagerCode: string,
    BookingType: string,
    WastagePercent: number,
    Amount: number,
    SFlag: string,
    SParty: string,
    BillNo: number,
    ImgID: string,
    UpdateOn: Date,
    VAPercent: number,
    ItemAmount: number,
    GSCode: number,
    FinYear: number,
    ItemwiseTaxPercentage: number,
    ItemwiseTaxAmount: number,
    MCPerPiece: string,
    ProductID: string,
    IsIssued: string,
    CounterCode: string,
    SalCode: string,
    MCPercent: number,
    MCType: string,
    EstNo: string,
}
